In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from matplotlib import pyplot
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import KFold, cross_val_score
from numpy import mean

In [2]:
fnamesIPcam = ["D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-23.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-24.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-25.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-26.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-27.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-28.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-29.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-30.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-11-21.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Netatmo_unsw16-09-23.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Netatmo_unsw16-09-24.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Netatmo_unsw16-09-25.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Netatmo_unsw16-09-26.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Netatmo_unsw16-09-27.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Netatmo_unsw16-09-28.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Netatmo_unsw16-09-29.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Netatmo_unsw16-09-30.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Netatmo_unsw16-11-21.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/SamsungSmarCam_unsw16-09-23.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/SamsungSmarCam_unsw16-09-24.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/SamsungSmarCam_unsw16-09-25.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/SamsungSmarCam_unsw16-09-26.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/SamsungSmarCam_unsw16-09-27.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/SamsungSmarCam_unsw16-09-28.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/SamsungSmarCam_unsw16-09-29.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/SamsungSmarCam_unsw16-09-30.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/SamsungSmarCam_unsw16-11-21.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/TP-LinkCamera_unsw16-09-23.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/TP-LinkCamera_unsw16-09-24.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/TP-LinkCamera_unsw16-09-25.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/TP-LinkCamera_unsw16-09-26.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/TP-LinkCamera_unsw16-09-27.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/TP-LinkCamera_unsw16-09-28.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/TP-LinkCamera_unsw16-09-29.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/TP-LinkCamera_unsw16-09-30.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/WithingsBabyMonitor_unsw16-09-23.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/WithingsBabyMonitor_unsw16-09-24.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/WithingsBabyMonitor_unsw16-09-25.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/WithingsBabyMonitor_unsw16-09-26.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/WithingsBabyMonitor_unsw16-09-27.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/WithingsBabyMonitor_unsw16-09-28.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/WithingsBabyMonitor_unsw16-09-29.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/WithingsBabyMonitor_unsw16-09-30.pcap_Flow.csv",
          ]

In [3]:
dfList = list()
for fname in fnamesIPcam: 
    data = pd.read_csv(fname)
    print('file:', fname, ' data size: ',data.shape)
    dfList.append(data)
############## combine the data frames
ipcamDF = pd.concat(dfList)
print(ipcamDF.shape)

file: D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-23.pcap_Flow.csv  data size:  (722, 84)
file: D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-24.pcap_Flow.csv  data size:  (754, 84)
file: D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-25.pcap_Flow.csv  data size:  (721, 84)
file: D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-26.pcap_Flow.csv  data size:  (747, 84)
file: D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-27.pcap_Flow.csv  data size:  (722, 84)
file: D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-28.pcap_Flow.csv  data size:  (746, 84)
file: D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-29.pcap_Flow.csv  data size:  (721, 84)
file: D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-30.pcap_Flow.csv  data size:  (722, 84)
file: D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-11-21.pcap_Flow.csv  data size:  (722, 84)
file: D:/Springer_IJIS/UNSWpcap/csvfiles/Netatmo_unsw16-09-23.pcap_Flow.csv  data size:  (2071, 84)
file: D:/

In [4]:
#see unique labels
print(list(ipcamDF['Label'].unique()))

['Dropcam', 'NetatmoCam', 'SamsungSmartCam', 'TPLinkCam', 'WithingsCam']


In [5]:
ipcamDF['Label'].replace('No Label','IPCam',inplace=True)
#uniqueLabels = list(ipcamDF['Label'].unique())
#print(uniqueLabels)
print(list(ipcamDF['Label'].unique()))

['Dropcam', 'NetatmoCam', 'SamsungSmartCam', 'TPLinkCam', 'WithingsCam']


In [6]:
######### creating master DF
dfListAll = [ipcamDF]#,shareDF, confDF, otherDF]
masterDF = pd.concat(dfListAll)
print(masterDF.shape)

(109932, 84)


In [7]:
#discard all those columns that helps in uniquely identifying a flow
masterPruned = masterDF.iloc[:,np.arange(7,84)]
print('pruneddata size: ', masterPruned.shape)
ftList = list(masterPruned.columns)
print(ftList)

pruneddata size:  (109932, 77)
['Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b A

In [8]:
uniqueLabels = list(masterDF['Label'].unique())
print(uniqueLabels)

['Dropcam', 'NetatmoCam', 'SamsungSmartCam', 'TPLinkCam', 'WithingsCam']


In [9]:
#discard all those columns that helps in uniquely identifying a flow
masterPruned = masterDF.iloc[:,np.arange(7,84)]
print('pruneddata size: ', masterPruned.shape)
ftList = list(masterPruned.columns)
print(ftList)

pruneddata size:  (109932, 77)
['Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b A

In [10]:
#discard those flows that has 0 flow duration
masterSelected = masterPruned.drop(masterPruned[masterPruned['Flow Duration']==0].index)
masterSelected.shape

(109932, 77)

In [11]:
#identify those columns that has non-numeric values
typesList = masterSelected.dtypes
ftCount = len(ftList)
nonNumericFtList = list()
for fi in range(ftCount):
    if ftList[fi] != 'Label' and typesList[fi] != 'int64' and typesList[fi] != 'float64':
        print(ftList[fi], '  ', typesList[fi])
        nonNumericFtList.append(ftList[fi])
print(nonNumericFtList)

[]


In [12]:
for ft in nonNumericFtList:
    masterSelected[ft] = pd.to_numeric(masterSelected[ft], errors='coerce')

In [13]:
print(nonNumericFtList)
for ft in nonNumericFtList:
    countNaN = masterSelected[ft].isna().sum()
    print('converted to numeric ft: ', ft, '  countNaN: ', countNaN)

[]


In [14]:
number_inf = masterSelected[masterSelected == np.inf].count().sum()
print('count inf: ',number_inf)

count inf:  0


In [15]:
typesList = masterSelected.dtypes
ftCount = len(ftList)
nonNumericFtList = list()
for fi in range(ftCount):
    if ftList[fi] != 'Label' and typesList[fi] != 'int64' and typesList[fi] != 'float64':
        print(ftList[fi], '  ', typesList[fi])
        nonNumericFtList.append(ftList[fi])
print(nonNumericFtList)

[]


In [16]:
#identify those columns that has 0 std
count = 0
staticFtList = list()
for ft in ftList:
    if ft == 'Label':
        continue
    #print('ft : ', ft)
    ftMin = masterSelected[ft].min()
    ftMax = masterSelected[ft].max()
    #std = masterPruned[ft].std()
    
    if ftMin == ftMax:
        count += 1
        print('count: ', count, ' ft: ', ft, ' ftmin: ', ftMin, ' ftMax: ', ftMax)
        staticFtList.append(ft)
print(staticFtList)

count:  1  ft:  Fwd PSH Flags  ftmin:  0  ftMax:  0
count:  2  ft:  Fwd URG Flags  ftmin:  0  ftMax:  0
count:  3  ft:  Bwd URG Flags  ftmin:  0  ftMax:  0
count:  4  ft:  URG Flag Cnt  ftmin:  0  ftMax:  0
count:  5  ft:  CWE Flag Count  ftmin:  0  ftMax:  0
count:  6  ft:  ECE Flag Cnt  ftmin:  0  ftMax:  0
count:  7  ft:  Fwd Byts/b Avg  ftmin:  0  ftMax:  0
count:  8  ft:  Fwd Pkts/b Avg  ftmin:  0  ftMax:  0
count:  9  ft:  Fwd Blk Rate Avg  ftmin:  0  ftMax:  0
count:  10  ft:  Bwd Byts/b Avg  ftmin:  0  ftMax:  0
count:  11  ft:  Bwd Pkts/b Avg  ftmin:  0  ftMax:  0
count:  12  ft:  Bwd Blk Rate Avg  ftmin:  0  ftMax:  0
count:  13  ft:  Init Fwd Win Byts  ftmin:  -1  ftMax:  -1
count:  14  ft:  Fwd Seg Size Min  ftmin:  0  ftMax:  0
['Fwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg', 'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Init Fwd Win Byts', 'Fwd Seg Size 

In [17]:
#remove those columns that have 0 std
print('before droping column: ', masterSelected.shape)
for ft in staticFtList:
    masterSelected.drop([ft], axis=1,inplace=True)
print('after droping column: ', masterSelected.shape)  

before droping column:  (109932, 77)
after droping column:  (109932, 63)


In [18]:
xCount = masterSelected.shape[1]
print(xCount)
finalFtList = list(masterSelected.columns)
print(finalFtList)

63
['Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Bwd PSH Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Subflow Fwd Pkts', 'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle 

In [19]:
#report intermediate data frame to a csv
masterSelected.to_csv('C:/Users/Priyanka/Desktop/iCamInspector_GithubRepository/Code/ProcessedNPrunnedAllCombination_UNSW.csv', index = False)

In [20]:
#classification with all the features
masterDS = masterSelected.values
X = masterDS[:,:-1]
Y = masterDS[:,-1]
print("Xshape: ", X.shape)
print("Yshape: ", Y.shape)

Xshape:  (109932, 62)
Yshape:  (109932,)


Extra Tree Classifier

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [22]:
# Building the model
extra_tree_forest = ExtraTreesClassifier(n_estimators = 5, criterion ='entropy', max_features = xCount)

In [23]:
# Training the model
extra_tree_forest.fit(X, Y)

ExtraTreesClassifier(criterion='entropy', max_features=63, n_estimators=5)

In [24]:
# Computing the importance of each feature
feature_importance = extra_tree_forest.feature_importances_

In [25]:
# Normalizing the individual importances
feature_importance_normalized = np.std([tree.feature_importances_ for tree in
                                        extra_tree_forest.estimators_],
                                        axis = 0)

In [26]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.ensemble import ExtraTreesClassifier
from numpy import mean
from numpy import std

In [27]:
# evaluate the model
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(extra_tree_forest, X, Y, scoring='accuracy', cv=cv, n_jobs=1, error_score='raise')
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

Accuracy: 0.998 (0.000)


In [28]:
y_pred = extra_tree_forest.predict(X_test)

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 1637     0     0     0     0]
 [    0  4293     0     0     0]
 [    0     0 15384     0     0]
 [    0     1     0  2653     0]
 [    0     0     0     0  3515]]


0.9999636138703926

In [30]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

                 precision    recall  f1-score   support

        Dropcam       1.00      1.00      1.00      1637
     NetatmoCam       1.00      1.00      1.00      4293
SamsungSmartCam       1.00      1.00      1.00     15384
      TPLinkCam       1.00      1.00      1.00      2654
    WithingsCam       1.00      1.00      1.00      3515

       accuracy                           1.00     27483
      macro avg       1.00      1.00      1.00     27483
   weighted avg       1.00      1.00      1.00     27483



Guassian Naive Bays Classifier

In [31]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=.25, random_state=50)

In [32]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import numpy as np

In [33]:
clf = GaussianNB()
clf.fit(x_train, y_train.flatten())

GaussianNB()

In [34]:
predictions = clf.predict(x_test)
print('Accuracy Score: ', accuracy_score(predictions, y_test))

Accuracy Score:  0.3410835789397082


In [35]:
from sklearn.metrics import confusion_matrix 
cm = confusion_matrix(y_test, predictions) 
print(cm)

[[ 1595     3     5    11    22]
 [    1  1992   291    13  1974]
 [    4    24   827  3148 11358]
 [    0     2   122  1441  1120]
 [    0     8     3     0  3519]]


In [36]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

                 precision    recall  f1-score   support

        Dropcam       1.00      0.97      0.99      1636
     NetatmoCam       0.98      0.47      0.63      4271
SamsungSmartCam       0.66      0.05      0.10     15361
      TPLinkCam       0.31      0.54      0.39      2685
    WithingsCam       0.20      1.00      0.33      3530

       accuracy                           0.34     27483
      macro avg       0.63      0.61      0.49     27483
   weighted avg       0.64      0.34      0.29     27483



KNN Classifier

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [38]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test) #avoid data leakage

In [39]:
from math import sqrt
class KNN():
  def __init__(self,k):
    self.k=k
    print(self.k)
  def fit(self,X_train,y_train):
    self.x_train=X_train
    self.y_train=y_train
  def calculate_euclidean(self,sample1,sample2):
    distance=0.0
    for i in range(len(sample1)):
      distance+=(sample1[i]-sample2[i])**2 #Euclidean Distance = sqrt(sum i to N (x1_i – x2_i)^2)
    return sqrt(distance)
  def nearest_neighbors(self,test_sample):
    distances=[]#calculate distances from a test sample to every sample in a training set
    for i in range(len(self.x_train)):
      distances.append((self.y_train[i],self.calculate_euclidean(self.x_train[i],test_sample)))
    distances.sort(key=lambda x:x[1])#sort in ascending order, based on a distance value
    neighbors=[]
    for i in range(self.k): #get first k samples
      neighbors.append(distances[i][0])
    return neighbors
  def predict(self,test_set):
    predictions=[]
    for test_sample in test_set:
      neighbors=self.nearest_neighbors(test_sample)
      labels=[sample for sample in neighbors]
      prediction=max(labels,key=labels.count)
      predictions.append(prediction)
    return predictions

In [40]:
model=KNN(5) #our model
model.fit(X_train,y_train)

5


In [41]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)#The default metric is minkowski, and with p=2 is equivalent to the standard Euclidean metric.
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [42]:
y_pred = classifier.predict(X_test)

In [43]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 1621     6     9     1     0]
 [    0  4264    26     2     1]
 [   13    28 15339     3     1]
 [    6    14    10  2623     1]
 [    2     5     2     0  3506]]


0.9952698031510389

In [44]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

                 precision    recall  f1-score   support

        Dropcam       0.99      0.99      0.99      1637
     NetatmoCam       0.99      0.99      0.99      4293
SamsungSmartCam       1.00      1.00      1.00     15384
      TPLinkCam       1.00      0.99      0.99      2654
    WithingsCam       1.00      1.00      1.00      3515

       accuracy                           1.00     27483
      macro avg       0.99      0.99      0.99     27483
   weighted avg       1.00      1.00      1.00     27483



Decision Tree Classifier

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

In [46]:
#max tree depth = 10
depth = 11 #run the cells of 19, 20, 21 for the other values of depth -- to generate plot
clf = DecisionTreeClassifier(max_depth = depth, random_state = 42)
#scores = cross_val_score(clf, X, Y, cv=10)
#print(scores)

In [47]:
score_list = cross_val_score(clf, X, Y, cv=10)

In [48]:
print('score list: ', score_list)
print('depth = ', depth, ' avg. score = ', np.average(score_list), ' std. score: ', np.std(score_list))

score list:  [0.98444606 0.9859014  0.99536068 0.95569908 0.99254071 0.99335941
 0.98817429 0.99608842 0.99581552 0.98635495]
depth =  11  avg. score =  0.9873740530568339  std. score:  0.011354418802149864


In [49]:
#create train and test set 
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

In [50]:
depth = 11 #take final depth from above analysis
clf = DecisionTreeClassifier(max_depth = depth, random_state = 42)
clf.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=11, random_state=42)

In [51]:
test_pred_decision_tree = clf.predict(X_test)

In [52]:
confusion_matrix = metrics.confusion_matrix(y_test, test_pred_decision_tree)
print(confusion_matrix)

[[ 2111    10    20     1     1]
 [    1  5559    90    16     2]
 [    5    17 20394    14     5]
 [    1     9    11  3406     2]
 [    0    11    12     0  4580]]


In [53]:
accuracy = metrics.accuracy_score(y_test, test_pred_decision_tree)
precision = metrics.precision_score(y_test, test_pred_decision_tree, average=None)
recall = metrics.recall_score(y_test, test_pred_decision_tree, average =None)
f1 = metrics.f1_score(y_test, test_pred_decision_tree, average=None)

print('accuracy = ', accuracy, ' precision: ', precision, ' recall: ', recall, '  f1: ',f1)

accuracy =  0.9937151992943382  precision:  [0.996695   0.99161613 0.99352073 0.99098051 0.99782135]  recall:  [0.98506766 0.98076923 0.99799364 0.99329251 0.99500326]   f1:  [0.99084722 0.98616285 0.99575216 0.99213516 0.99641031]


LKSVM Classifier

In [54]:
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Load the dataset
icam = pd.read_csv('D:/Springer_IJIS/ML_code_output/ProcessedNPrunnedAllCombination_UNSW_LKSVM.csv') #UNSW dataset

# Splitting the data into features and labels
X = icam.iloc[:, :-1]
y = icam.iloc[:, -1]

# Scaling the features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Splitting the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=109)

# Create a svm Classifier
clf = SVC(kernel='linear') 

# Train the model using the training sets
clf.fit(X_train, y_train)

# Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9674344140013826


Random Forest Classifier

In [55]:
# split data into training and testing sets

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.33, random_state = 42)

In [56]:
# check the shape of X_train and X_test
X_train.shape, X_test.shape

((73654, 62), (36278, 62))

In [57]:
#from sklearn.preprocessing import CategoricalEncoder
import category_encoders as ce

In [58]:
# encode categorical variables with ordinal encoding

encoder = ce.OrdinalEncoder(cols=[])
X_train = encoder.fit_transform(X_train)
X_test = encoder.transform(X_test)

In [59]:
# import Random Forest classifier

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# instantiate the classifier 
rfc = RandomForestClassifier(random_state=0)

# fit the model
rfc.fit(X_train, y_train)

# Predict the Test set results
y_pred = rfc.predict(X_test)

# Check accuracy score 
print('Model accuracy score with 10 decision-trees : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))
#Model accuracy score with 10 decision-trees : 0.9247

Model accuracy score with 10 decision-trees : 0.9972


In [60]:
# instantiate the classifier with n_estimators = 100
rfc_100 = RandomForestClassifier(n_estimators=100, random_state=0)

# fit the model to the training set
rfc_100.fit(X_train, y_train)

# Predict on the test set results
y_pred_100 = rfc_100.predict(X_test)

# Check accuracy score 
print('Model accuracy score with 100 decision-trees : {0:0.4f}'. format(accuracy_score(y_test, y_pred_100)))

Model accuracy score with 100 decision-trees : 0.9972


In [61]:
# create the classifier with n_estimators = 100
clf = RandomForestClassifier(n_estimators=100, random_state=0)

# fit the model to the training set
clf.fit(X_train, y_train)

RandomForestClassifier(random_state=0)

In [62]:
# Print the Confusion Matrix and slice it into four pieces

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix\n\n', cm)


Confusion matrix

 [[ 2128     1    13     1     0]
 [    2  5625    37     2     2]
 [   10    17 20404     3     1]
 [    0     3     4  3422     0]
 [    0     1     3     0  4599]]


XGBoost Classifier

In [19]:
ipcamDF['Label'].replace('Dropcam','0',inplace=True)
#uniqueLabels = list(ipcamDF['Label'].unique())
#print(uniqueLabels)
print(list(ipcamDF['Label'].unique()))

['0', 'NetatmoCam', 'SamsungSmartCam', 'TPLinkCam', 'WithingsCam']


In [20]:
ipcamDF['Label'].replace('NetatmoCam','1',inplace=True)
#uniqueLabels = list(ipcamDF['Label'].unique())
#print(uniqueLabels)
print(list(ipcamDF['Label'].unique()))

['0', '1', 'SamsungSmartCam', 'TPLinkCam', 'WithingsCam']


In [21]:
ipcamDF['Label'].replace('SamsungSmartCam','2',inplace=True)
#uniqueLabels = list(ipcamDF['Label'].unique())
#print(uniqueLabels)
print(list(ipcamDF['Label'].unique()))

['0', '1', '2', 'TPLinkCam', 'WithingsCam']


In [22]:
ipcamDF['Label'].replace('TPLinkCam','3',inplace=True)
#uniqueLabels = list(ipcamDF['Label'].unique())
#print(uniqueLabels)
print(list(ipcamDF['Label'].unique()))

['0', '1', '2', '3', 'WithingsCam']


In [23]:
ipcamDF['Label'].replace('WithingsCam','4',inplace=True)
#uniqueLabels = list(ipcamDF['Label'].unique())
#print(uniqueLabels)
print(list(ipcamDF['Label'].unique()))

['0', '1', '2', '3', '4']


In [24]:
######### creating master DF
dfListAll = [ipcamDF]
masterDF = pd.concat(dfListAll)
print(masterDF.shape)

(109932, 84)


In [25]:
uniqueLabels = list(masterDF['Label'].unique())
print(uniqueLabels)

['0', '1', '2', '3', '4']


In [26]:
#discard all those columns that helps in uniquely identifying a flow
masterPruned = masterDF.iloc[:,np.arange(7,84)]
print('pruneddata size: ', masterPruned.shape)
ftList = list(masterPruned.columns)
print(ftList)

pruneddata size:  (109932, 77)
['Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b A

In [27]:
#discard those flows that has 0 flow duration
masterSelected = masterPruned.drop(masterPruned[masterPruned['Flow Duration']==0].index)
masterSelected.shape

(109932, 77)

In [28]:
#identify those columns that has non-numeric values
typesList = masterSelected.dtypes
ftCount = len(ftList)
nonNumericFtList = list()
for fi in range(ftCount):
    if ftList[fi] != 'Label' and typesList[fi] != 'int64' and typesList[fi] != 'float64':
        print(ftList[fi], '  ', typesList[fi])
        nonNumericFtList.append(ftList[fi])
print(nonNumericFtList)

[]


In [29]:
for ft in nonNumericFtList:
    masterSelected[ft] = pd.to_numeric(masterSelected[ft], errors='coerce')

In [30]:
print(nonNumericFtList)
for ft in nonNumericFtList:
    countNaN = masterSelected[ft].isna().sum()
    print('converted to numeric ft: ', ft, '  countNaN: ', countNaN)

[]


In [31]:
number_inf = masterSelected[masterSelected == np.inf].count().sum()
print('count inf: ',number_inf)

count inf:  0


In [32]:
typesList = masterSelected.dtypes
ftCount = len(ftList)
nonNumericFtList = list()
for fi in range(ftCount):
    if ftList[fi] != 'Label' and typesList[fi] != 'int64' and typesList[fi] != 'float64':
        print(ftList[fi], '  ', typesList[fi])
        nonNumericFtList.append(ftList[fi])
print(nonNumericFtList)

[]


In [33]:
#identify those columns that has 0 std
count = 0
staticFtList = list()
for ft in ftList:
    if ft == 'Label':
        continue
    #print('ft : ', ft)
    ftMin = masterSelected[ft].min()
    ftMax = masterSelected[ft].max()
    #std = masterPruned[ft].std()
    
    if ftMin == ftMax:
        count += 1
        print('count: ', count, ' ft: ', ft, ' ftmin: ', ftMin, ' ftMax: ', ftMax)
        staticFtList.append(ft)
print(staticFtList)

count:  1  ft:  Fwd PSH Flags  ftmin:  0  ftMax:  0
count:  2  ft:  Fwd URG Flags  ftmin:  0  ftMax:  0
count:  3  ft:  Bwd URG Flags  ftmin:  0  ftMax:  0
count:  4  ft:  URG Flag Cnt  ftmin:  0  ftMax:  0
count:  5  ft:  CWE Flag Count  ftmin:  0  ftMax:  0
count:  6  ft:  ECE Flag Cnt  ftmin:  0  ftMax:  0
count:  7  ft:  Fwd Byts/b Avg  ftmin:  0  ftMax:  0
count:  8  ft:  Fwd Pkts/b Avg  ftmin:  0  ftMax:  0
count:  9  ft:  Fwd Blk Rate Avg  ftmin:  0  ftMax:  0
count:  10  ft:  Bwd Byts/b Avg  ftmin:  0  ftMax:  0
count:  11  ft:  Bwd Pkts/b Avg  ftmin:  0  ftMax:  0
count:  12  ft:  Bwd Blk Rate Avg  ftmin:  0  ftMax:  0
count:  13  ft:  Init Fwd Win Byts  ftmin:  -1  ftMax:  -1
count:  14  ft:  Fwd Seg Size Min  ftmin:  0  ftMax:  0
['Fwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg', 'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Init Fwd Win Byts', 'Fwd Seg Size 

In [34]:
#remove those columns that have 0 std
print('before droping column: ', masterSelected.shape)
for ft in staticFtList:
    masterSelected.drop([ft], axis=1,inplace=True)
print('after droping column: ', masterSelected.shape)    

before droping column:  (109932, 77)
after droping column:  (109932, 63)


In [35]:
xCount = masterSelected.shape[1]
print(xCount)
finalFtList = list(masterSelected.columns)
print(finalFtList)

63
['Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Bwd PSH Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Subflow Fwd Pkts', 'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle 

In [36]:
#report intermediate data frame to a csv
masterSelected.to_csv('C:/Users/Priyanka/Desktop/iCamInspector_GithubRepository/Code/ProcessedNPrunnedAllCombination_UNSW_XGBoost.csv', index = False)

In [37]:
import pandas as pd
masterSelected=pd.read_csv('C:/Users/Priyanka/Desktop/iCamInspector_GithubRepository/Code/ProcessedNPrunnedAllCombination_UNSW_XGBoost.csv')

In [38]:
print(list(masterSelected['Label'].unique()))

[0, 1, 2, 3, 4]


In [39]:
#classification with all the features
masterDS = masterSelected.values
X = masterDS[:,:-1]
Y = masterDS[:,-1]
print("Xshape: ", X.shape)
print("Yshape: ", Y.shape)

Xshape:  (109932, 62)
Yshape:  (109932,)


In [40]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)
#y_train_xgb = y_train.map({"IPCam": 0, "Other":1, "VConf":2, "VShare": 3})
#X_train, X_test, y_train, y_test = train_test_split(X, Y, Label, test_size=test_size, stratify = labels)

#xgb = XGBClassifier(n_estimators = 400, learning_rate = 0.1, max_depth = 3)
#xgb.fit(X_train.values, y_train)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)
print(y_train.shape)

(82449,)


In [41]:
#import XGBClassifier
from xgboost import XGBClassifier
# declare parameters
params = {
            'objective':'binary:logistic',
            'max_depth': 4,
            #'alpha': 0.1,
            'learning_rate': 1.0,
            'n_estimators':250
         }
                      
# instantiate the classifier 
xgb_clf = XGBClassifier(**params)

# fit the classifier to the training data
xgb_clf.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=1.0, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=250, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [42]:
#alternatively view the parameters of the xgb trained model
print(xgb_clf)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=1.0, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=250, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)


In [43]:
# make predictions on test data
y_pred = xgb_clf.predict(X_test)
print(y_pred.shape)

(27483,)


In [44]:
# check accuracy score
from sklearn.metrics import accuracy_score
print('XGBoost model accuracy score: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

XGBoost model accuracy score: 0.9982


In [45]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred) #our model
print(cm)
accuracy_score(y_test, y_pred)

[[ 1624     2    11     0     0]
 [    0  4288     4     1     0]
 [    6    11 15363     4     0]
 [    0     5     3  2645     1]
 [    0     0     1     0  3514]]


0.9982170796492377