In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from matplotlib import pyplot

In [2]:
fnames = ["D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet1_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet2_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet3_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet4_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet5_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet6_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet7_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet8_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet9_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet10_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet11_Flow.csv",
          #"D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet12_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/MSTeams1_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/MSTeams2_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/MSTeams11_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/MSTeams12_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/MSTeams21_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/MSTeams22_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_1_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_2_Flow.csv",
          #"D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_3_Flow.csv",
          #"D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_4_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_5_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_6_Flow.csv",
          #"D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_7_Flow.csv",
          #"D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_8_Flow.csv",
          #"D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_9_Flow.csv",
          #"D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_10_Flow.csv",
          #"D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_11_Flow.csv",
          #"D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_12_Flow.csv",
          #"D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_13_Flow.csv",
          #"D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_14_Flow.csv",
          #"D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_15_Flow.csv",
          #"D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/Skype/New collection/csv/Skype1_filtered_Flow.csv",
          #"D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/Skype/New collection/csv/Skype2_filtered_Flow.csv",
          #"D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/Skype/New collection/csv/Skype3_filtered_Flow.csv",
          #"D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/Skype/New collection/csv/Skype4_filtered_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/zoom1_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/zoom2_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/zoom3_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/zoom4_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/zoom5_Flow.csv",
          #"D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/zoom_6_Flow.csv",
          #"D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/zoom_7_Flow.csv",
          #"D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/zoom_8_Flow.csv",
         ]

In [3]:
dfList = list()
for fname in fnames: 
    data = pd.read_csv(fname)
    print('file:', fname, ' data size: ',data.shape)
    dfList.append(data)
############## combine the data frames
masterDF = pd.concat(dfList)
print(masterDF.shape)

file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet1_Flow.csv  data size:  (2620, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet2_Flow.csv  data size:  (3350, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet3_Flow.csv  data size:  (3207, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet4_Flow.csv  data size:  (6585, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet5_Flow.csv  data size:  (331, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet6_Flow.csv  data size:  (4937, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet7_Flow.csv  data size:  (1436, 84)


In [4]:
#see unique labels
masterDF['Label'].unique()
masterDF['Label'].replace('VConf_Gmeet','VConf_GMeet',inplace=True)
uniqueLabels = list(masterDF['Label'].unique())
print(uniqueLabels)

['VConf_GMeet', 'VConf_Teams', 'VConf_Skype', 'VConf_Zoom']


In [5]:
#discard all those columns that helps in uniquely identifying a flow
masterPruned = masterDF.iloc[:,np.arange(7,84)]
print('pruneddata size: ', masterPruned.shape)
ftList = list(masterPruned.columns)
print(ftList)

pruneddata size:  (40025, 77)
['Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Av

In [6]:
#discard those flows that has 0 flow duration
masterSelected = masterPruned.drop(masterPruned[masterPruned['Flow Duration']==0].index)
masterSelected.shape

(38857, 77)

In [7]:
#identify those columns that has non-numeric values
typesList = masterSelected.dtypes
ftCount = len(ftList)
nonNumericFtList = list()
for fi in range(ftCount):
    if ftList[fi] != 'Label' and typesList[fi] != 'int64' and typesList[fi] != 'float64':
        print(ftList[fi], '  ', typesList[fi])
        nonNumericFtList.append(ftList[fi])
print(nonNumericFtList)

[]


In [8]:
#pyplot.boxplot(results, labels=names, showmeans=True)
#pyplot.scatter(fpackets,fbytes)
#pyplot.show()


In [9]:
for ft in nonNumericFtList:
    masterSelected[ft] = pd.to_numeric(masterSelected[ft], errors='coerce')

In [10]:
print(nonNumericFtList)
for ft in nonNumericFtList:
    countNaN = masterSelected[ft].isna().sum()
    print('converted to numeric ft: ', ft, '  countNaN: ', countNaN)

[]


In [11]:
number_inf = masterSelected[masterSelected == np.inf].count().sum()
print('count inf: ',number_inf)

count inf:  0


In [12]:
typesList = masterSelected.dtypes
ftCount = len(ftList)
nonNumericFtList = list()
for fi in range(ftCount):
    if ftList[fi] != 'Label' and typesList[fi] != 'int64' and typesList[fi] != 'float64':
        print(ftList[fi], '  ', typesList[fi])
        nonNumericFtList.append(ftList[fi])
print(nonNumericFtList)

[]


In [13]:
#identify those columns that has 0 std
count = 0
staticFtList = list()
for ft in ftList:
    if ft == 'Label':
        continue
    #print('ft : ', ft)
    ftMin = masterSelected[ft].min()
    ftMax = masterSelected[ft].max()
    #std = masterPruned[ft].std()
    
    if ftMin == ftMax:
        count += 1
        print('count: ', count, ' ft: ', ft, ' ftmin: ', ftMin, ' ftMax: ', ftMax)
        staticFtList.append(ft)
print(staticFtList)

count:  1  ft:  Fwd PSH Flags  ftmin:  0  ftMax:  0
count:  2  ft:  Fwd URG Flags  ftmin:  0  ftMax:  0
count:  3  ft:  Bwd URG Flags  ftmin:  0  ftMax:  0
count:  4  ft:  URG Flag Cnt  ftmin:  0  ftMax:  0
count:  5  ft:  CWE Flag Count  ftmin:  0  ftMax:  0
count:  6  ft:  ECE Flag Cnt  ftmin:  0  ftMax:  0
count:  7  ft:  Fwd Byts/b Avg  ftmin:  0  ftMax:  0
count:  8  ft:  Fwd Pkts/b Avg  ftmin:  0  ftMax:  0
count:  9  ft:  Fwd Blk Rate Avg  ftmin:  0  ftMax:  0
count:  10  ft:  Bwd Byts/b Avg  ftmin:  0  ftMax:  0
count:  11  ft:  Bwd Pkts/b Avg  ftmin:  0  ftMax:  0
count:  12  ft:  Bwd Blk Rate Avg  ftmin:  0  ftMax:  0
count:  13  ft:  Init Fwd Win Byts  ftmin:  -1  ftMax:  -1
count:  14  ft:  Fwd Seg Size Min  ftmin:  0  ftMax:  0
['Fwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg', 'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Init Fwd Win Byts', 'Fwd Seg Size 

In [14]:
#remove those columns that have 0 std
print('before droping column: ', masterSelected.shape)
for ft in staticFtList:
    masterSelected.drop([ft], axis=1,inplace=True)
print('after droping column: ', masterSelected.shape)    


before droping column:  (38857, 77)
after droping column:  (38857, 63)


In [15]:
xCount = masterSelected.shape[1]
print(xCount)
finalFtList = list(masterSelected.columns)
print(finalFtList)

63
['Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Bwd PSH Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Subflow Fwd Pkts', 'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle 

In [16]:
#report intermediate data frame to a csv
masterSelected.to_csv('D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/ProcessedNPrunnedAllConf_04012023.csv', index = False)

In [17]:
#classification with all the features
masterDS = masterSelected.values
X = masterDS[:,:-1]
Y = masterDS[:,-1]
print("Xshape: ", X.shape)
print("Yshape: ", Y.shape)

Xshape:  (38857, 62)
Yshape:  (38857,)


In [18]:
clf = DecisionTreeClassifier(random_state=10)
#print('classification with all features:')
start_time = time.time()
print(f'{start_time:.2f}s start time')
scores = cross_val_score(clf, X, Y, cv=10)
clf.fit(X_train, Y_train)
elapsed_time = time.time() - start_time
print(f'{elapsed_time:.2f}s elapsed during training')
#print(scores)
#print('mean score: ', scores.mean(), 'min score: ', scores.min(), 'max score: ', scores.max(), ' std score: ', scores.std())

NameError: name 'time' is not defined

In [31]:
import time
#performance with all features using decision tree
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=1)
model = DecisionTreeClassifier(random_state=10)
clf = model.fit(X_train,Y_train)
start_time = time.time()
print(f'{start_time:.2f}s start time')
yhat = model.predict(X_test)
elapsed_time = time.time() - start_time
print(f'{elapsed_time:.2f}s elapsed during training')

1673498645.03s start time
0.06s elapsed during training


In [20]:
import time

#performance with all features using decision tree
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=1)
start_time = time.time()
print(f'{start_time:.2f}s start time')
model = DecisionTreeClassifier(random_state=10)
clf = model.fit(X_train,Y_train)
elapsed_time = time.time() - start_time
print(f'{elapsed_time:.2f}s elapsed during training')
yhat = model.predict(X_test)

1673498299.75s start time
1.29s elapsed during training


In [79]:
import time

start_time = time.time()
print(f'{start_time:.2f}s start time')

1672992110.01s start time


In [93]:
#performance with all features using decision tree
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=1)
model = DecisionTreeClassifier(random_state=0)
#decision_tree = model.fit(X_train,Y_train)
clf = model.fit(X_train,Y_train)
yhat = model.predict(X_test)
print(yhat.shape)
print(X_train.shape)

(12823,)
(26034, 62)


In [81]:
import time

clf.fit(X_train, Y_train)
elapsed_time = time.time() - start_time
print(f'{elapsed_time:.2f}s elapsed during training')

3.05s elapsed during training


In [20]:
from sklearn.tree import export_text
from sklearn import tree
#r = export_text(decision_tree, feature_names=finalFtList)
#print(r)
text_representation = tree.export_text(clf)
print(text_representation)

|--- feature_28 <= 15.50
|   |--- feature_1 <= 4.50
|   |   |--- feature_31 <= 122.00
|   |   |   |--- feature_23 <= 5131795.50
|   |   |   |   |--- feature_52 <= 509.50
|   |   |   |   |   |--- feature_34 <= 277.50
|   |   |   |   |   |   |--- feature_39 <= 0.50
|   |   |   |   |   |   |   |--- feature_33 <= 21.73
|   |   |   |   |   |   |   |   |--- feature_32 <= 0.02
|   |   |   |   |   |   |   |   |   |--- feature_32 <= 0.02
|   |   |   |   |   |   |   |   |   |   |--- class: VConf_GMeet
|   |   |   |   |   |   |   |   |   |--- feature_32 >  0.02
|   |   |   |   |   |   |   |   |   |   |--- feature_60 <= 20000000.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: VConf_Skype
|   |   |   |   |   |   |   |   |   |   |--- feature_60 >  20000000.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: VConf_Zoom
|   |   |   |   |   |   |   |   |--- feature_32 >  0.02
|   |   |   |   |   |   |   |   |   |--- feature_16 <= 1573788.25
|   |   |   |   |   |   |   |   |   |   |---

In [21]:
print(clf.tree_.max_depth)

36


In [22]:
conf_mat = metrics.confusion_matrix(Y_test, yhat,labels=uniqueLabels)
#[i][j] ==> knwon to be in group i and predicted as group j
print(conf_mat)
print('Meet as Meet = ',conf_mat[0][0],' percent = ', (conf_mat[0][0]/(conf_mat[0][0]+conf_mat[0][1]+conf_mat[0][2]+conf_mat[0][3])))
print('Meet as Team = ',conf_mat[0][1],' percent = ', (conf_mat[0][1]/(conf_mat[0][0]+conf_mat[0][1]+conf_mat[0][2]+conf_mat[0][3])))
print('Meet as Skype = ',conf_mat[0][2],' percent = ', (conf_mat[0][2]/(conf_mat[0][0]+conf_mat[0][1]+conf_mat[0][2]+conf_mat[0][3])))
print('Meet as Zoom = ',conf_mat[0][3],' percent = ', (conf_mat[0][3]/(conf_mat[0][0]+conf_mat[0][1]+conf_mat[0][2]+conf_mat[0][3])))
print('\n')

print('Team as Meet = ',conf_mat[1][0],' percent = ', (conf_mat[1][0]/(conf_mat[1][0]+conf_mat[1][1]+conf_mat[1][2]+conf_mat[1][3])))
print('Team as Team = ',conf_mat[1][1],' percent = ', (conf_mat[1][1]/(conf_mat[1][0]+conf_mat[1][1]+conf_mat[1][2]+conf_mat[1][3])))
print('Team as Skype =',conf_mat[1][2],' percent = ', (conf_mat[1][2]/(conf_mat[1][0]+conf_mat[1][1]+conf_mat[1][2]+conf_mat[1][3])))
print('Team as Zoom = ',conf_mat[1][3],' percent = ', (conf_mat[1][3]/(conf_mat[1][0]+conf_mat[1][1]+conf_mat[1][2]+conf_mat[1][3])))
print('\n')

print('Skype as Meet = ',conf_mat[2][0],' percent = ', (conf_mat[2][0]/(conf_mat[2][0]+conf_mat[2][1]+conf_mat[2][2]+conf_mat[2][3])))
print('Skype as Team = ',conf_mat[2][1],' percent = ', (conf_mat[2][1]/(conf_mat[2][0]+conf_mat[2][1]+conf_mat[2][2]+conf_mat[2][3])))
print('Skype as Skype = ',conf_mat[2][2],' percent = ', (conf_mat[2][2]/(conf_mat[2][0]+conf_mat[2][1]+conf_mat[2][2]+conf_mat[2][3])))
print('Skype as Zoom = ',conf_mat[2][3],' percent = ', (conf_mat[2][3]/(conf_mat[2][0]+conf_mat[2][1]+conf_mat[2][2]+conf_mat[2][3])))
print('\n')

print('Zoom as Meet = ',conf_mat[3][0],' percent = ', (conf_mat[3][0]/(conf_mat[3][0]+conf_mat[3][1]+conf_mat[3][2]+conf_mat[3][3])))
print('Zoom as Team = ',conf_mat[3][1],' percent = ', (conf_mat[3][1]/(conf_mat[3][0]+conf_mat[3][1]+conf_mat[3][2]+conf_mat[3][3])))
print('Zoom as Skype = ',conf_mat[3][2],' percent = ', (conf_mat[3][2]/(conf_mat[3][0]+conf_mat[3][1]+conf_mat[3][2]+conf_mat[3][3])))
print('Zoom as Zoom = ',conf_mat[3][3],' percent = ', (conf_mat[3][3]/(conf_mat[3][0]+conf_mat[3][1]+conf_mat[3][2]+conf_mat[3][3])))

[[9899  131   41   41]
 [  60 2063    0   12]
 [  43   19  202    6]
 [  44   36    3  223]]
Meet as Meet =  9899  percent =  0.978935917721519
Meet as Team =  131  percent =  0.012954905063291139
Meet as Skype =  41  percent =  0.004054588607594937
Meet as Zoom =  41  percent =  0.004054588607594937


Team as Meet =  60  percent =  0.02810304449648712
Team as Team =  2063  percent =  0.9662763466042155
Team as Skype = 0  percent =  0.0
Team as Zoom =  12  percent =  0.005620608899297424


Skype as Meet =  43  percent =  0.15925925925925927
Skype as Team =  19  percent =  0.07037037037037037
Skype as Skype =  202  percent =  0.7481481481481481
Skype as Zoom =  6  percent =  0.022222222222222223


Zoom as Meet =  44  percent =  0.1437908496732026
Zoom as Team =  36  percent =  0.11764705882352941
Zoom as Skype =  3  percent =  0.00980392156862745
Zoom as Zoom =  223  percent =  0.7287581699346405


In [23]:
# feature selection using ANNOVA F-score
topKval = 10
FS = SelectKBest(score_func=f_classif, k=topKval)
#print(type(FS))
# learn relationship from training data
FS.fit(X, Y)
# transform train input data
XNew = FS.transform(X)
# transform test input data
print('XNew.shape', XNew.shape)
#print('XNew', XNew)

XNew.shape (38857, 10)


In [24]:
#find selected features
namesFilter = FS.get_support()
features =  np.array(finalFtList)
names = list()#features[0:-1]
scores = list()
for fi in range(xCount-1):
    if (fi < xCount-1) and (FS.get_support()[fi]) and (not np.isnan(FS.scores_[fi])):
        #print('i = ', fi, ' ftName: ', ftList[fi], ' FS.support_: ', FS.get_support()[fi], ' FS.scores: = ', FS.scores_[fi])
        scores.append(FS.scores_[fi])
        names.append(features[fi])
names_scores = list(zip(names, scores))
ns_df = pd.DataFrame(data = names_scores, columns=['Feat_names', 'F_Scores'])
#print(ns_df)
#Sort the dataframe for better visualization
ns_df_sorted = ns_df.sort_values(['F_Scores', 'Feat_names'], ascending = [False, True])
print('features df shape: ', ns_df_sorted.shape, '  \nfeatures df top 10 rows: \n', ns_df_sorted.head(topKval))
#restFtList = list()
#for ft in finalFtList:
#    if ft not in names:
#        restFtList.append(ft)
#    else:
#        print(ft)

features df shape:  (10, 2)   
features df top 10 rows: 
          Feat_names     F_Scores
6      Pkt Len Mean  1426.537693
7      Pkt Size Avg  1401.525268
0     Flow Duration  1143.376434
2   Bwd Pkt Len Min   834.795026
5      Flow IAT Max   809.325806
1  Fwd Pkt Len Mean   769.292332
8  Fwd Seg Size Avg   769.292332
4     Flow IAT Mean   749.966419
3  Bwd Pkt Len Mean   747.385645
9  Bwd Seg Size Avg   747.385645


In [25]:
print('classification with top 10 selected features:')
scores = cross_val_score(clf, XNew, Y, cv=10)
print(scores)
print('mean score: ', scores.mean(),'min score: ', scores.min(), 'max score: ', scores.max(), ' std score: ', scores.std())

classification with top 10 selected features:
[0.9372105  0.9379825  0.92871848 0.94467319 0.94827586 0.92408646
 0.9500772  0.89317889 0.91042471 0.94259974]
mean score:  0.9317227535601186 min score:  0.8931788931788932 max score:  0.9500772002058672  std score:  0.017241774566739136


In [26]:
#performance with to k  features using decision tree
X_train, X_test, Y_train, Y_test = train_test_split(XNew, Y, test_size=0.33, random_state=1)
model = DecisionTreeClassifier(random_state=0)
clf1 = model.fit(X_train,Y_train)
ypred = model.predict(X_test)

In [27]:
from sklearn.tree import export_text
from sklearn import tree

text_representation = tree.export_text(clf1)
print(text_representation)

|--- feature_7 <= 317.75
|   |--- feature_4 <= 3766691.12
|   |   |--- feature_2 <= 60.00
|   |   |   |--- feature_5 <= 158.50
|   |   |   |   |--- feature_0 <= 74.50
|   |   |   |   |   |--- feature_4 <= 28.25
|   |   |   |   |   |   |--- feature_0 <= 22.50
|   |   |   |   |   |   |   |--- feature_5 <= 17.50
|   |   |   |   |   |   |   |   |--- feature_4 <= 8.75
|   |   |   |   |   |   |   |   |   |--- feature_4 <= 5.50
|   |   |   |   |   |   |   |   |   |   |--- class: VConf_Skype
|   |   |   |   |   |   |   |   |   |--- feature_4 >  5.50
|   |   |   |   |   |   |   |   |   |   |--- feature_4 <= 7.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: VConf_GMeet
|   |   |   |   |   |   |   |   |   |   |--- feature_4 >  7.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: VConf_GMeet
|   |   |   |   |   |   |   |   |--- feature_4 >  8.75
|   |   |   |   |   |   |   |   |   |--- class: VConf_Skype
|   |   |   |   |   |   |   |--- feature_5 >  17.50
|   |   |   |   |   |  

In [28]:
print(clf1.tree_.max_depth)

38


In [29]:
conf_mat = metrics.confusion_matrix(Y_test, ypred,labels=uniqueLabels)
#[i][j] ==> knwon to be in group i and predicted as group j
print(conf_mat)
print('Meet as Meet = ',conf_mat[0][0],' percent = ', (conf_mat[0][0]/(conf_mat[0][0]+conf_mat[0][1]+conf_mat[0][2]+conf_mat[0][3])))
print('Meet as Team = ',conf_mat[0][1],' percent = ', (conf_mat[0][1]/(conf_mat[0][0]+conf_mat[0][1]+conf_mat[0][2]+conf_mat[0][3])))
print('Meet as Skype = ',conf_mat[0][2],' percent = ', (conf_mat[0][2]/(conf_mat[0][0]+conf_mat[0][1]+conf_mat[0][2]+conf_mat[0][3])))
print('Meet as Zoom = ',conf_mat[0][3],' percent = ', (conf_mat[0][3]/(conf_mat[0][0]+conf_mat[0][1]+conf_mat[0][2]+conf_mat[0][3])))
print('\n')

print('Team as Meet = ',conf_mat[1][0],' percent = ', (conf_mat[1][0]/(conf_mat[1][0]+conf_mat[1][1]+conf_mat[1][2]+conf_mat[1][3])))
print('Team as Team = ',conf_mat[1][1],' percent = ', (conf_mat[1][1]/(conf_mat[1][0]+conf_mat[1][1]+conf_mat[1][2]+conf_mat[1][3])))
print('Team as Skype =',conf_mat[1][2],' percent = ', (conf_mat[1][2]/(conf_mat[1][0]+conf_mat[1][1]+conf_mat[1][2]+conf_mat[1][3])))
print('Team as Zoom = ',conf_mat[1][3],' percent = ', (conf_mat[1][3]/(conf_mat[1][0]+conf_mat[1][1]+conf_mat[1][2]+conf_mat[1][3])))
print('\n')

print('Skype as Meet = ',conf_mat[2][0],' percent = ', (conf_mat[2][0]/(conf_mat[2][0]+conf_mat[2][1]+conf_mat[2][2]+conf_mat[2][3])))
print('Skype as Team = ',conf_mat[2][1],' percent = ', (conf_mat[2][1]/(conf_mat[2][0]+conf_mat[2][1]+conf_mat[2][2]+conf_mat[2][3])))
print('Skype as Skype = ',conf_mat[2][2],' percent = ', (conf_mat[2][2]/(conf_mat[2][0]+conf_mat[2][1]+conf_mat[2][2]+conf_mat[2][3])))
print('Skype as Zoom = ',conf_mat[2][3],' percent = ', (conf_mat[2][3]/(conf_mat[2][0]+conf_mat[2][1]+conf_mat[2][2]+conf_mat[2][3])))
print('\n')

print('Zoom as Meet = ',conf_mat[3][0],' percent = ', (conf_mat[3][0]/(conf_mat[3][0]+conf_mat[3][1]+conf_mat[3][2]+conf_mat[3][3])))
print('Zoom as Team = ',conf_mat[3][1],' percent = ', (conf_mat[3][1]/(conf_mat[3][0]+conf_mat[3][1]+conf_mat[3][2]+conf_mat[3][3])))
print('Zoom as Skype = ',conf_mat[3][2],' percent = ', (conf_mat[3][2]/(conf_mat[3][0]+conf_mat[3][1]+conf_mat[3][2]+conf_mat[3][3])))
print('Zoom as Zoom = ',conf_mat[3][3],' percent = ', (conf_mat[3][3]/(conf_mat[3][0]+conf_mat[3][1]+conf_mat[3][2]+conf_mat[3][3])))


[[9737  238   82   55]
 [ 253 1867   12    3]
 [ 108   26  128    8]
 [  72   39    4  191]]
Meet as Meet =  9737  percent =  0.9629153481012658
Meet as Team =  238  percent =  0.02353639240506329
Meet as Skype =  82  percent =  0.008109177215189873
Meet as Zoom =  55  percent =  0.005439082278481013


Team as Meet =  253  percent =  0.11850117096018735
Team as Team =  1867  percent =  0.8744730679156909
Team as Skype = 12  percent =  0.005620608899297424
Team as Zoom =  3  percent =  0.001405152224824356


Skype as Meet =  108  percent =  0.4
Skype as Team =  26  percent =  0.0962962962962963
Skype as Skype =  128  percent =  0.4740740740740741
Skype as Zoom =  8  percent =  0.02962962962962963


Zoom as Meet =  72  percent =  0.23529411764705882
Zoom as Team =  39  percent =  0.12745098039215685
Zoom as Skype =  4  percent =  0.013071895424836602
Zoom as Zoom =  191  percent =  0.6241830065359477


In [30]:
#classification with unselected and uncorrelated features
corr = masterSelected.corr()
corr.shape

(62, 62)

In [50]:
corrThreshold = 0.65
unCorrUnSelFtList = list()
for ft1 in finalFtList:#baseft = 'Idle Max' for each of the selected features
    #print('ft1: ', ft1)
    isCorr = False
    for ft2 in names:# for each of the top 10 features
        if ft1 == 'Label' or ft2 == 'Label' or (ft1 == ft2):
            continue
        elif abs(corr[ft1][ft2]) > corrThreshold:
                isCorr = True
                print('ft1: ', ft1, 'ft2: ', ft2, '  corr: ', corr[ft1][ft2])
                break
    if not isCorr and ft1 not in unCorrUnSelFtList:
        #print('corr[{0}][{1}] = {2}: isPresentInRestFtlist: {3}'.format(baseft,ft,corr[baseft][ft], ft in restFtList))
        unCorrUnSelFtList.append(ft1)
        
    #elif abs(corr[ft1][ft] >= 0.6 and ft in unCorrUnSelFtList):
    #            unCorrUnSelFtList.remove(ft)
print(len(unCorrUnSelFtList))
print(unCorrUnSelFtList)

print(len(names))
print(names)

ft1:  Flow Duration ft2:  Flow IAT Max   corr:  0.6577915432927807
ft1:  Fwd Pkt Len Max ft2:  Fwd Pkt Len Mean   corr:  0.7405867998501936
ft1:  Fwd Pkt Len Mean ft2:  Pkt Len Mean   corr:  0.7579520725431108
ft1:  Fwd Pkt Len Std ft2:  Fwd Pkt Len Mean   corr:  0.7491422582493634
ft1:  Bwd Pkt Len Max ft2:  Bwd Pkt Len Mean   corr:  0.6720308717774695
ft1:  Bwd Pkt Len Mean ft2:  Pkt Len Mean   corr:  0.7366215246371286
ft1:  Bwd Pkt Len Std ft2:  Bwd Pkt Len Mean   corr:  0.6605817928725299
ft1:  Flow IAT Std ft2:  Flow IAT Max   corr:  0.8337262302919508
ft1:  Flow IAT Max ft2:  Flow Duration   corr:  0.6577915432927807
ft1:  Flow IAT Min ft2:  Flow IAT Mean   corr:  0.8713047350407235
ft1:  Fwd IAT Tot ft2:  Flow Duration   corr:  0.9138763611697057
ft1:  Fwd IAT Mean ft2:  Flow IAT Max   corr:  0.6614533868425196
ft1:  Fwd IAT Std ft2:  Flow IAT Max   corr:  0.6773206428417271
ft1:  Fwd IAT Max ft2:  Flow IAT Max   corr:  0.8400513288393031
ft1:  Bwd IAT Tot ft2:  Flow Duration  

In [51]:
for ft1 in names:
    for ft2 in unCorrUnSelFtList:
        if ft1 != 'Label' or ft2 == 'Label':
            continue
        if abs(corr[ft][ft2]) >= corrThreshold:
            print('ft: ',ft, ' ft2: ',ft2, corr[ft][ft2])

In [52]:
#slice master data frame to only uncorrelated and unselected features
masterUnSelected = masterSelected[unCorrUnSelFtList]
print(masterUnSelected.shape)

(38857, 36)


In [53]:
#### classification with unselected columns
masterUnSelDS = masterUnSelected.values
Xnotsel = masterUnSelDS[:,:-1]
Y = masterUnSelDS[:,-1]
print("Xshape: ", Xnotsel.shape)
print("Yshape: ", Y.shape)

Xshape:  (38857, 35)
Yshape:  (38857,)


In [54]:
#find cross validation score with uncorrelated and unselecte feature data frame
clf = DecisionTreeClassifier(random_state=0)
print('classification with rest (not top 10) features:')
scores = cross_val_score(clf, X, Y, cv=10)
print(scores)
print('mean score: ', scores.mean(), ' std score: ', scores.std())

classification with rest (not top 10) features:
[0.96525991 0.95599588 0.97735461 0.97375193 0.96628924 0.96500257
 0.97632527 0.92972973 0.96396396 0.97297297]
mean score:  0.9646646079945104  std score:  0.013220464863811053


In [55]:
#classification with with uncorrelated and unselecte feature data frame
X_train, X_test, Y_train, Y_test = train_test_split(Xnotsel, Y, test_size=0.33, random_state=1)
model = DecisionTreeClassifier(random_state=0)
model.fit(X_train,Y_train)
yhat = model.predict(X_test)

In [56]:
conf_mat = metrics.confusion_matrix(Y_test, yhat,labels=uniqueLabels)
#[i][j] ==> knwon to be in group i and predicted as group j
print(conf_mat)
print('Meet as Meet = ',conf_mat[0][0],' percent = ', (conf_mat[0][0]/(conf_mat[0][0]+conf_mat[0][1]+conf_mat[0][2]+conf_mat[0][3])))
print('Meet as Team = ',conf_mat[0][1],' percent = ', (conf_mat[0][1]/(conf_mat[0][0]+conf_mat[0][1]+conf_mat[0][2]+conf_mat[0][3])))
print('Meet as Skype = ',conf_mat[0][2],' percent = ', (conf_mat[0][2]/(conf_mat[0][0]+conf_mat[0][1]+conf_mat[0][2]+conf_mat[0][3])))
print('Meet as Zoom = ',conf_mat[0][3],' percent = ', (conf_mat[0][3]/(conf_mat[0][0]+conf_mat[0][1]+conf_mat[0][2]+conf_mat[0][3])))
print('\n')

print('Team as Meet = ',conf_mat[1][0],' percent = ', (conf_mat[1][0]/(conf_mat[1][0]+conf_mat[1][1]+conf_mat[1][2]+conf_mat[1][3])))
print('Team as Team = ',conf_mat[1][1],' percent = ', (conf_mat[1][1]/(conf_mat[1][0]+conf_mat[1][1]+conf_mat[1][2]+conf_mat[1][3])))
print('Team as Skype =',conf_mat[1][2],' percent = ', (conf_mat[1][2]/(conf_mat[1][0]+conf_mat[1][1]+conf_mat[1][2]+conf_mat[1][3])))
print('Team as Zoom = ',conf_mat[1][3],' percent = ', (conf_mat[1][3]/(conf_mat[1][0]+conf_mat[1][1]+conf_mat[1][2]+conf_mat[1][3])))
print('\n')

print('Skype as Meet = ',conf_mat[2][0],' percent = ', (conf_mat[2][0]/(conf_mat[2][0]+conf_mat[2][1]+conf_mat[2][2]+conf_mat[2][3])))
print('Skype as Team = ',conf_mat[2][1],' percent = ', (conf_mat[2][1]/(conf_mat[2][0]+conf_mat[2][1]+conf_mat[2][2]+conf_mat[2][3])))
print('Skype as Skype = ',conf_mat[2][2],' percent = ', (conf_mat[2][2]/(conf_mat[2][0]+conf_mat[2][1]+conf_mat[2][2]+conf_mat[2][3])))
print('Skype as Zoom = ',conf_mat[2][3],' percent = ', (conf_mat[2][3]/(conf_mat[2][0]+conf_mat[2][1]+conf_mat[2][2]+conf_mat[2][3])))
print('\n')

print('Zoom as Meet = ',conf_mat[3][0],' percent = ', (conf_mat[3][0]/(conf_mat[3][0]+conf_mat[3][1]+conf_mat[3][2]+conf_mat[3][3])))
print('Zoom as Team = ',conf_mat[3][1],' percent = ', (conf_mat[3][1]/(conf_mat[3][0]+conf_mat[3][1]+conf_mat[3][2]+conf_mat[3][3])))
print('Zoom as Skype = ',conf_mat[3][2],' percent = ', (conf_mat[3][2]/(conf_mat[3][0]+conf_mat[3][1]+conf_mat[3][2]+conf_mat[3][3])))
print('Zoom as Zoom = ',conf_mat[3][3],' percent = ', (conf_mat[3][3]/(conf_mat[3][0]+conf_mat[3][1]+conf_mat[3][2]+conf_mat[3][3])))

[[9905  133   32   42]
 [  66 2048    6   15]
 [  48   17  197    8]
 [  33   41    3  229]]
Meet as Meet =  9905  percent =  0.9795292721518988
Meet as Team =  133  percent =  0.013152689873417722
Meet as Skype =  32  percent =  0.0031645569620253164
Meet as Zoom =  42  percent =  0.004153481012658227


Team as Meet =  66  percent =  0.030913348946135833
Team as Team =  2048  percent =  0.9592505854800937
Team as Skype = 6  percent =  0.002810304449648712
Team as Zoom =  15  percent =  0.00702576112412178


Skype as Meet =  48  percent =  0.17777777777777778
Skype as Team =  17  percent =  0.06296296296296296
Skype as Skype =  197  percent =  0.7296296296296296
Skype as Zoom =  8  percent =  0.02962962962962963


Zoom as Meet =  33  percent =  0.10784313725490197
Zoom as Team =  41  percent =  0.13398692810457516
Zoom as Skype =  3  percent =  0.00980392156862745
Zoom as Zoom =  229  percent =  0.7483660130718954
