In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from matplotlib import pyplot

In [3]:
fnamesUnswIPcam = ["D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-23.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-24.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-25.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-26.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-27.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-28.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-29.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-30.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-11-21.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Netatmo_unsw16-09-23.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Netatmo_unsw16-09-24.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Netatmo_unsw16-09-25.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Netatmo_unsw16-09-26.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Netatmo_unsw16-09-27.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Netatmo_unsw16-09-28.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Netatmo_unsw16-09-29.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Netatmo_unsw16-09-30.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/Netatmo_unsw16-11-21.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/SamsungSmarCam_unsw16-09-23.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/SamsungSmarCam_unsw16-09-24.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/SamsungSmarCam_unsw16-09-25.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/SamsungSmarCam_unsw16-09-26.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/SamsungSmarCam_unsw16-09-27.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/SamsungSmarCam_unsw16-09-28.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/SamsungSmarCam_unsw16-09-29.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/SamsungSmarCam_unsw16-09-30.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/SamsungSmarCam_unsw16-11-21.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/TP-LinkCamera_unsw16-09-23.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/TP-LinkCamera_unsw16-09-24.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/TP-LinkCamera_unsw16-09-25.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/TP-LinkCamera_unsw16-09-26.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/TP-LinkCamera_unsw16-09-27.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/TP-LinkCamera_unsw16-09-28.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/TP-LinkCamera_unsw16-09-29.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/TP-LinkCamera_unsw16-09-30.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/WithingsBabyMonitor_unsw16-09-23.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/WithingsBabyMonitor_unsw16-09-24.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/WithingsBabyMonitor_unsw16-09-25.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/WithingsBabyMonitor_unsw16-09-26.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/WithingsBabyMonitor_unsw16-09-27.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/WithingsBabyMonitor_unsw16-09-28.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/WithingsBabyMonitor_unsw16-09-29.pcap_Flow.csv",
          "D:/Springer_IJIS/UNSWpcap/csvfiles/WithingsBabyMonitor_unsw16-09-30.pcap_Flow.csv",
          ]
fnamesIPcam = ["D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/alarmClockCam_1_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/alarmClockCam_2_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/alarmClockCam_3_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/alarmClockCam_4_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/canarycam_1_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/canarycam_2_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/canarycam_3_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/canarycam_4_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/d3dtraffic_1_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/d3dtraffic_2_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/d3dtraffic_3_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/ezviz_1_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/ezviz_2_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/ezviz_3_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/ezviz_4_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/ezviz_5_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/ezviz_6_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/ezviz_7_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/netatmocam1_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/netatmocam2_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/netatmocam3_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/v380Cam1_1_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/v380Cam1_2_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/v380Cam1_3_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/v380Cam1_4_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/v380Cam1_5_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/v380Cam1_6_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/v380Cam1_7_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/v380Cam1_8_Flow.csv"]
fnamesConf = [
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet1_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet2_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet3_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet4_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet5_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet6_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet7_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet8_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet9_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet10_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet11_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet12_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/MSTeams1_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/MSTeams2_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/MSTeams11_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/MSTeams12_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/MSTeams21_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/MSTeams22_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_1_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_2_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_3_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_4_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_5_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_6_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_7_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_8_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_9_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_10_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_11_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_12_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_13_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_14_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/Skype_15_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/zoom1_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/zoom2_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/zoom3_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/zoom4_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/zoom5_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/zoom_6_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/zoom_7_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/zoom_8_Flow.csv",
          ]
fnamesShare = [
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoSharing_filteredpcapcsv/amazon1_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoSharing_filteredpcapcsv/amazon2_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoSharing_filteredpcapcsv/amazon3_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoSharing_filteredpcapcsv/amazon4_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoSharing_filteredpcapcsv/amazon5_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoSharing_filteredpcapcsv/YouTube_1_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoSharing_filteredpcapcsv/YouTube_2_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoSharing_filteredpcapcsv/YouTube_3_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoSharing_filteredpcapcsv/YouTube_4_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoSharing_filteredpcapcsv/YouTube_5_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoSharing_filteredpcapcsv/YouTube_6_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoSharing_filteredpcapcsv/YouTube_7_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoSharing_filteredpcapcsv/YouTube_8_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoSharing_filteredpcapcsv/YouTube_9_Flow.csv",
         ]
fnamesOther = [
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/Skype/New collection/Other data/csv/other1_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/Skype/New collection/Other data/csv/other2_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/Skype/New collection/Other data/csv/other3_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/Skype/New collection/Other data/csv/other4_Flow.csv",
          "D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/Skype/New collection/Other data/csv/other3_Flow.csv",
         ]

In [4]:
dfList = list()
for fname in fnamesIPcam: 
    data = pd.read_csv(fname)
    print('file:', fname, ' data size: ',data.shape)
    dfList.append(data)
############## combine the data frames
ipcamDF = pd.concat(dfList)
print(ipcamDF.shape)

file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/alarmClockCam_1_Flow.csv  data size:  (125, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/alarmClockCam_2_Flow.csv  data size:  (157, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/alarmClockCam_3_Flow.csv  data size:  (95, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/alarmClockCam_4_Flow.csv  data size:  (18, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/canarycam_1_Flow.csv  data size:  (45, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/canarycam_2_Flow.csv  data size:  (45, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/IPCamera_filteredpcapcsv/canarycam_3_Flow.csv  data size:  (143, 84)
file: D:/New pcaps_IoT

In [5]:
#see unique labels
print(list(ipcamDF['Label'].unique()))

['IPCam_AlarmClock', 'IPCam_Canary', 'IPCam_D3D', 'IPCam_Ezviz', 'IPCam_Netatmo', 'IPCam_V380']


In [6]:
ipcamDF['Label'].replace('IPCam_AlarmClock','IPCam',inplace=True)
#uniqueLabels = list(ipcamDF['Label'].unique())
#print(uniqueLabels)
print(list(ipcamDF['Label'].unique()))

['IPCam', 'IPCam_Canary', 'IPCam_D3D', 'IPCam_Ezviz', 'IPCam_Netatmo', 'IPCam_V380']


In [7]:
ipcamDF['Label'].replace('IPCam_Canary','IPCam',inplace=True)
#uniqueLabels = list(ipcamDF['Label'].unique())
#print(uniqueLabels)
print(list(ipcamDF['Label'].unique()))

['IPCam', 'IPCam_D3D', 'IPCam_Ezviz', 'IPCam_Netatmo', 'IPCam_V380']


In [8]:
ipcamDF['Label'].replace('IPCam_D3D','IPCam',inplace=True)
#uniqueLabels = list(ipcamDF['Label'].unique())
#print(uniqueLabels)
print(list(ipcamDF['Label'].unique()))

['IPCam', 'IPCam_Ezviz', 'IPCam_Netatmo', 'IPCam_V380']


In [9]:
ipcamDF['Label'].replace('IPCam_Ezviz','IPCam',inplace=True)
#uniqueLabels = list(ipcamDF['Label'].unique())
#print(uniqueLabels)
print(list(ipcamDF['Label'].unique()))

['IPCam', 'IPCam_Netatmo', 'IPCam_V380']


In [10]:
ipcamDF['Label'].replace('IPCam_Netatmo','IPCam',inplace=True)
#uniqueLabels = list(ipcamDF['Label'].unique())
#print(uniqueLabels)
print(list(ipcamDF['Label'].unique()))

['IPCam', 'IPCam_V380']


In [11]:
ipcamDF['Label'].replace('IPCam_V380','IPCam',inplace=True)
uniqueLabels = list(ipcamDF['Label'].unique())
print(uniqueLabels)
#print(list(ipcamDF['Label'].unique()))

['IPCam']


In [12]:
###################################\
dfList = list()
for fname in fnamesShare: 
    data = pd.read_csv(fname)
    print('file:', fname, ' data size: ',data.shape)
    dfList.append(data)
############## combine the data frames
shareDF = pd.concat(dfList)
print(shareDF.shape)

file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoSharing_filteredpcapcsv/amazon1_Flow.csv  data size:  (870, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoSharing_filteredpcapcsv/amazon2_Flow.csv  data size:  (516, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoSharing_filteredpcapcsv/amazon3_Flow.csv  data size:  (921, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoSharing_filteredpcapcsv/amazon4_Flow.csv  data size:  (467, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoSharing_filteredpcapcsv/amazon5_Flow.csv  data size:  (800, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoSharing_filteredpcapcsv/YouTube_1_Flow.csv  data size:  (1420, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoSharing_filteredpcapcsv/YouTube_2_Flow.csv  data size:  (52, 84)
file: D:/New pcaps_IoTSpyCamer

In [13]:
print(list(shareDF['Label'].unique()))

['VShare_Amazon', 'VShare_YouTube']


In [14]:
shareDF['Label'].replace('VShare_Amazon','VShare',inplace=True)
#uniqueLabels = list(ipcamDF['Label'].unique())
#print(uniqueLabels)
print(list(shareDF['Label'].unique()))

['VShare', 'VShare_YouTube']


In [15]:
shareDF['Label'].replace('VShare_YouTube','VShare',inplace=True)
uniqueLabels = list(shareDF['Label'].unique())
print(uniqueLabels)

['VShare']


In [16]:
###################################\
dfList = list()
for fname in fnamesConf: 
    data = pd.read_csv(fname)
    print('file:', fname, ' data size: ',data.shape)
    dfList.append(data)
############## combine the data frames
confDF = pd.concat(dfList)
print(confDF.shape)

file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet1_Flow.csv  data size:  (2620, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet2_Flow.csv  data size:  (3350, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet3_Flow.csv  data size:  (3207, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet4_Flow.csv  data size:  (6585, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet5_Flow.csv  data size:  (331, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet6_Flow.csv  data size:  (4937, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/filteredPcapCSV/VideoConferencing_filteredpcapcsv/gmeet7_Flow.csv  data size:  (1436, 84)


In [17]:
print(list(confDF['Label'].unique()))

['VConf_GMeet', 'VConf_Teams', 'VConf_Skype', 'VConf_Zoom']


In [18]:
confDF['Label'].replace('VConf_GMeet','VConf',inplace=True)
#uniqueLabels = list(ipcamDF['Label'].unique())
#print(uniqueLabels)
print(list(confDF['Label'].unique()))

['VConf', 'VConf_Teams', 'VConf_Skype', 'VConf_Zoom']


In [19]:
confDF['Label'].replace('VConf_Teams','VConf',inplace=True)
#uniqueLabels = list(ipcamDF['Label'].unique())
#print(uniqueLabels)
print(list(confDF['Label'].unique()))

['VConf', 'VConf_Skype', 'VConf_Zoom']


In [20]:
confDF['Label'].replace('VConf_Skype','VConf',inplace=True)
#uniqueLabels = list(ipcamDF['Label'].unique())
#print(uniqueLabels)
print(list(confDF['Label'].unique()))

['VConf', 'VConf_Zoom']


In [21]:
confDF['Label'].replace('VConf_Zoom','VConf',inplace=True)
uniqueLabels = list(confDF['Label'].unique())
print(uniqueLabels)

['VConf']


In [22]:
###################################\
dfList = list()
for fname in fnamesOther: 
    data = pd.read_csv(fname)
    print('file:', fname, ' data size: ',data.shape)
    dfList.append(data)
############## combine the data frames
otherDF = pd.concat(dfList)
print(otherDF.shape)

file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/Skype/New collection/Other data/csv/other1_Flow.csv  data size:  (12155, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/Skype/New collection/Other data/csv/other2_Flow.csv  data size:  (1795, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/Skype/New collection/Other data/csv/other3_Flow.csv  data size:  (11728, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/Skype/New collection/Other data/csv/other4_Flow.csv  data size:  (5358, 84)
file: D:/New pcaps_IoTSpyCamera/TDSC_WorkAfterReview/Skype/New collection/Other data/csv/other3_Flow.csv  data size:  (11728, 84)
(42764, 84)


In [23]:
print(list(otherDF['Label'].unique()))

['Other', 'No Label']


In [24]:
otherDF['Label'].replace('No Label','Other',inplace=True)
#uniqueLabels = list(ipcamDF['Label'].unique())
#print(uniqueLabels)
print(list(otherDF['Label'].unique()))

['Other']


In [25]:
print(list(otherDF['Label'].unique()))

['Other']


In [26]:
print(list(confDF['Label'].unique()))
print(list(shareDF['Label'].unique()))
print(list(ipcamDF['Label'].unique()))
print(list(otherDF['Label'].unique()))

['VConf']
['VShare']
['IPCam']
['Other']


In [27]:
dfList = list()
for fname in fnamesUnswIPcam: 
    data = pd.read_csv(fname)
    print('file:', fname, ' data size: ',data.shape)
    dfList.append(data)
############## combine the data frames
ipcamDF1 = pd.concat(dfList)
print(ipcamDF1.shape)

file: D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-23.pcap_Flow.csv  data size:  (722, 84)
file: D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-24.pcap_Flow.csv  data size:  (754, 84)
file: D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-25.pcap_Flow.csv  data size:  (721, 84)
file: D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-26.pcap_Flow.csv  data size:  (747, 84)
file: D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-27.pcap_Flow.csv  data size:  (722, 84)
file: D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-28.pcap_Flow.csv  data size:  (746, 84)
file: D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-29.pcap_Flow.csv  data size:  (721, 84)
file: D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-09-30.pcap_Flow.csv  data size:  (722, 84)
file: D:/Springer_IJIS/UNSWpcap/csvfiles/Dropcam_unsw16-11-21.pcap_Flow.csv  data size:  (722, 84)
file: D:/Springer_IJIS/UNSWpcap/csvfiles/Netatmo_unsw16-09-23.pcap_Flow.csv  data size:  (2071, 84)
file: D:/

In [28]:
#see unique labels
print(list(ipcamDF1['Label'].unique()))

['Dropcam', 'NetatmoCam', 'SamsungSmartCam', 'TPLinkCam', 'WithingsCam']


In [29]:
ipcamDF1['Label'].replace('IPCam_AlarmClock','IPCam',inplace=True)
#uniqueLabels = list(ipcamDF['Label'].unique())
#print(uniqueLabels)
print(list(ipcamDF1['Label'].unique()))

['Dropcam', 'NetatmoCam', 'SamsungSmartCam', 'TPLinkCam', 'WithingsCam']


In [30]:
######### creating master DF
dfListAll = [ipcamDF1,ipcamDF,shareDF, confDF, otherDF]
masterDF = pd.concat(dfListAll)
print(masterDF.shape)

(219627, 84)


In [31]:
uniqueLabels = list(masterDF['Label'].unique())
print(uniqueLabels)

['Dropcam', 'NetatmoCam', 'SamsungSmartCam', 'TPLinkCam', 'WithingsCam', 'IPCam', 'VShare', 'VConf', 'Other']


In [32]:
#discard all those columns that helps in uniquely identifying a flow
masterPruned = masterDF.iloc[:,np.arange(7,84)]
print('pruneddata size: ', masterPruned.shape)
ftList = list(masterPruned.columns)
print(ftList)

pruneddata size:  (219627, 77)
['Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b A

In [33]:
#discard those flows that has 0 flow duration
masterSelected = masterPruned.drop(masterPruned[masterPruned['Flow Duration']==0].index)
masterSelected.shape

(155734, 77)

In [34]:
#identify those columns that has non-numeric values
typesList = masterSelected.dtypes
ftCount = len(ftList)
nonNumericFtList = list()
for fi in range(ftCount):
    if ftList[fi] != 'Label' and typesList[fi] != 'int64' and typesList[fi] != 'float64':
        print(ftList[fi], '  ', typesList[fi])
        nonNumericFtList.append(ftList[fi])
print(nonNumericFtList)

[]


In [35]:
for ft in nonNumericFtList:
    masterSelected[ft] = pd.to_numeric(masterSelected[ft], errors='coerce')

In [36]:
print(nonNumericFtList)
for ft in nonNumericFtList:
    countNaN = masterSelected[ft].isna().sum()
    print('converted to numeric ft: ', ft, '  countNaN: ', countNaN)

[]


In [37]:
number_inf = masterSelected[masterSelected == np.inf].count().sum()
print('count inf: ',number_inf)

count inf:  0


In [38]:
typesList = masterSelected.dtypes
ftCount = len(ftList)
nonNumericFtList = list()
for fi in range(ftCount):
    if ftList[fi] != 'Label' and typesList[fi] != 'int64' and typesList[fi] != 'float64':
        print(ftList[fi], '  ', typesList[fi])
        nonNumericFtList.append(ftList[fi])
print(nonNumericFtList)

[]


In [39]:
#identify those columns that has 0 std
count = 0
staticFtList = list()
for ft in ftList:
    if ft == 'Label':
        continue
    #print('ft : ', ft)
    ftMin = masterSelected[ft].min()
    ftMax = masterSelected[ft].max()
    #std = masterPruned[ft].std()
    
    if ftMin == ftMax:
        count += 1
        print('count: ', count, ' ft: ', ft, ' ftmin: ', ftMin, ' ftMax: ', ftMax)
        staticFtList.append(ft)
print(staticFtList)

count:  1  ft:  Fwd PSH Flags  ftmin:  0  ftMax:  0
count:  2  ft:  Fwd URG Flags  ftmin:  0  ftMax:  0
count:  3  ft:  Bwd URG Flags  ftmin:  0  ftMax:  0
count:  4  ft:  URG Flag Cnt  ftmin:  0  ftMax:  0
count:  5  ft:  CWE Flag Count  ftmin:  0  ftMax:  0
count:  6  ft:  ECE Flag Cnt  ftmin:  0  ftMax:  0
count:  7  ft:  Fwd Byts/b Avg  ftmin:  0  ftMax:  0
count:  8  ft:  Fwd Pkts/b Avg  ftmin:  0  ftMax:  0
count:  9  ft:  Fwd Blk Rate Avg  ftmin:  0  ftMax:  0
count:  10  ft:  Bwd Byts/b Avg  ftmin:  0  ftMax:  0
count:  11  ft:  Bwd Pkts/b Avg  ftmin:  0  ftMax:  0
count:  12  ft:  Bwd Blk Rate Avg  ftmin:  0  ftMax:  0
count:  13  ft:  Init Fwd Win Byts  ftmin:  -1  ftMax:  -1
count:  14  ft:  Fwd Seg Size Min  ftmin:  0  ftMax:  0
['Fwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg', 'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Init Fwd Win Byts', 'Fwd Seg Size 

In [40]:
#remove those columns that have 0 std
print('before droping column: ', masterSelected.shape)
for ft in staticFtList:
    masterSelected.drop([ft], axis=1,inplace=True)
print('after droping column: ', masterSelected.shape)    

before droping column:  (155734, 77)
after droping column:  (155734, 63)


In [41]:
xCount = masterSelected.shape[1]
print(xCount)
finalFtList = list(masterSelected.columns)
print(finalFtList)

63
['Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Bwd PSH Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Subflow Fwd Pkts', 'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle 

In [42]:
#report intermediate data frame to a csv
masterSelected.to_csv('C:/Users/Priyanka/Desktop/iCamInspector_GithubRepository/Code/ProcessedNPrunnedAllCombination_ConbinationUNSWOurDataset.csv', index = False)

In [43]:
df = pd.read_csv('C:/Users/Priyanka/Desktop/iCamInspector_GithubRepository/Code/ProcessedNPrunnedAllCombination_ConbinationUNSWOurDataset.csv')

In [45]:
# Shuffle the dataset
df_shuffled = df.sample(n=len(df))

In [46]:
# Save the shuffled dataset to a new CSV file
df_shuffled.to_csv('C:/Users/Priyanka/Desktop/iCamInspector_GithubRepository/Code/ProcessedNPrunnedAllCombination_ConbinationUNSWOurDataset_Shuffleddataset_DT.csv', index=False)

In [47]:
df_shuffled = df_shuffled.reset_index(drop=True)

In [48]:
#classification with all the features
masterDS = df_shuffled.values  #masterSelected.values
X = masterDS[:,:-1]
Y = masterDS[:,-1]
print("Xshape: ", X.shape)
print("Yshape: ", Y.shape)

Xshape:  (155734, 62)
Yshape:  (155734,)


Decision Tree Classifier

In [49]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

In [50]:
#max tree depth = 10
depth = 11 #run the cells of 19, 20, 21 for the other values of depth -- to generate plot
clf = DecisionTreeClassifier(max_depth = depth, random_state = 42)
#scores = cross_val_score(clf, X, Y, cv=10)
#print(scores)

In [51]:
score_list = cross_val_score(clf, X, Y, cv=10)

In [52]:
print('score list: ', score_list)
print('depth = ', depth, ' avg. score = ', np.average(score_list), ' std. score: ', np.std(score_list))

score list:  [0.90445614 0.90606138 0.91184025 0.90503403 0.90714699 0.90650485
 0.90451422 0.90380787 0.90714699 0.90689013]
depth =  11  avg. score =  0.9063402851614535  std. score:  0.0021670763990788416


In [53]:
#create train and test set 
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

In [54]:
depth = 11 #take final depth from above analysis
clf = DecisionTreeClassifier(max_depth = depth, random_state = 42)
clf.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=11, random_state=42)

In [55]:
test_pred_decision_tree = clf.predict(X_test)

In [56]:
confusion_matrix = metrics.confusion_matrix(y_test, test_pred_decision_tree)
print(confusion_matrix)

[[ 1055     1     1    10     8     0     7     2     0]
 [    0  1133    49    72    17    19   218     7     1]
 [    4    37  3580   273    36     0    28     0     5]
 [    0   108    29 10268    38    30  1080    59    65]
 [    9    55     4    94 15366     0    74     1    10]
 [    0    14     0    10     5  2076     6     3   102]
 [    2   171    73   905    15    31  9450   107     1]
 [    0    32    56   457    10     0   309   547     0]
 [    0     0     1    14     1     0     8     0  3134]]


In [57]:
accuracy = metrics.accuracy_score(y_test, test_pred_decision_tree)
precision = metrics.precision_score(y_test, test_pred_decision_tree, average=None)
recall = metrics.recall_score(y_test, test_pred_decision_tree, average =None)
f1 = metrics.f1_score(y_test, test_pred_decision_tree, average=None)

In [58]:
print('accuracy = ', accuracy, ' precision: ', precision, ' recall: ', recall, '  f1: ',f1)

accuracy =  0.906913392874516  precision:  [0.98598131 0.73049645 0.94384392 0.8483847  0.99161074 0.96289425
 0.84525939 0.75344353 0.94454491]  recall:  [0.97324723 0.74736148 0.90335604 0.87933545 0.98417985 0.9368231
 0.87866109 0.38766832 0.99240025]   f1:  [0.97957289 0.73883274 0.92315627 0.86358284 0.98788132 0.94967978
 0.86163665 0.51193262 0.96788141]


Extra Tree Classifier

In [60]:
df = pd.read_csv('C:/Users/Priyanka/Desktop/iCamInspector_GithubRepository/Code/ProcessedNPrunnedAllCombination_ConbinationUNSWOurDataset.csv')

In [61]:
# Shuffle the dataset
df_shuffled = df.sample(n=len(df))

In [62]:
df = pd.read_csv('C:/Users/Priyanka/Desktop/iCamInspector_GithubRepository/Code/ProcessedNPrunnedAllCombination_ConbinationUNSWOurDataset.csv')

In [63]:
df_shuffled = df_shuffled.reset_index(drop=True)

In [64]:
#classification with all the features
masterDS = df_shuffled.values  #masterSelected.values
X = masterDS[:,:-1]
Y = masterDS[:,-1]
print("Xshape: ", X.shape)
print("Yshape: ", Y.shape)

Xshape:  (155734, 62)
Yshape:  (155734,)


In [65]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [66]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import KFold, cross_val_score
from numpy import mean

In [67]:
# Building the model
extra_tree_forest = ExtraTreesClassifier(n_estimators = 5, criterion ='entropy', max_features = xCount)

In [68]:
# Training the model
extra_tree_forest.fit(X, Y)

ExtraTreesClassifier(criterion='entropy', max_features=63, n_estimators=5)

In [69]:
# Computing the importance of each feature
feature_importance = extra_tree_forest.feature_importances_

In [70]:
# Normalizing the individual importances
feature_importance_normalized = np.std([tree.feature_importances_ for tree in
                                        extra_tree_forest.estimators_],
                                        axis = 0)

In [71]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.ensemble import ExtraTreesClassifier
from numpy import mean
from numpy import std

In [72]:
# evaluate the model
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(extra_tree_forest, X, Y, scoring='accuracy', cv=cv, n_jobs=1, error_score='raise')
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

Accuracy: 0.963 (0.001)


In [73]:
y_pred = extra_tree_forest.predict(X_test)

In [74]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  793     0     0     0     0     0     0     0     0]
 [    0  1134     0     0     0     0     0     0     0]
 [    0     0  2966     0     0     0     0     0     0]
 [    0     0     0  8700     0     0   124     9     0]
 [    0     0     1     0 11979     0     0     0     0]
 [    0     0     0     0     0  1630     0     0     0]
 [    0     0     0   268     0     0  8059     3     0]
 [    0     0     0    52     0     0    16   949     0]
 [    0     0     0     0     0     0     0     0  2251]]


0.987851235424051

In [75]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

                 precision    recall  f1-score   support

        Dropcam       1.00      1.00      1.00       793
          IPCam       1.00      1.00      1.00      1134
     NetatmoCam       1.00      1.00      1.00      2966
          Other       0.96      0.98      0.97      8833
SamsungSmartCam       1.00      1.00      1.00     11980
      TPLinkCam       1.00      1.00      1.00      1630
          VConf       0.98      0.97      0.98      8330
         VShare       0.99      0.93      0.96      1017
    WithingsCam       1.00      1.00      1.00      2251

       accuracy                           0.99     38934
      macro avg       0.99      0.99      0.99     38934
   weighted avg       0.99      0.99      0.99     38934



Guassian Naive Baise Classifier

In [76]:
df = pd.read_csv('C:/Users/Priyanka/Desktop/iCamInspector_GithubRepository/Code/ProcessedNPrunnedAllCombination_ConbinationUNSWOurDataset.csv')

In [77]:
# Shuffle the dataset
df_shuffled = df.sample(n=len(df))

In [78]:
# Save the shuffled dataset to a new CSV file
df_shuffled.to_csv('C:/Users/Priyanka/Desktop/iCamInspector_GithubRepository/Code/ProcessedNPrunnedAllCombination_ConbinationUNSWOurDataset.csv', index=False)

In [79]:
df_shuffled = df_shuffled.reset_index(drop=True)

In [80]:
#classification with all the features
masterDS = df_shuffled.values  #masterSelected.values
X = masterDS[:,:-1]
Y = masterDS[:,-1]
print("Xshape: ", X.shape)
print("Yshape: ", Y.shape)

Xshape:  (155734, 62)
Yshape:  (155734,)


In [81]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=.25, random_state=50)

In [82]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import numpy as np

In [83]:
clf = GaussianNB()
clf.fit(x_train, y_train.flatten())

GaussianNB()

In [84]:
predictions = clf.predict(x_test)
print('Accuracy Score: ', accuracy_score(predictions, y_test))

Accuracy Score:  0.2461601684902656


In [85]:
from sklearn.metrics import confusion_matrix 
cm = confusion_matrix(y_test, predictions) 
print(cm)

[[ 783    9    0    2    2    2    2    0   19]
 [   2   93  416   25   67  118    3   21  373]
 [   0    4 1332    7  161    3    1    0 1370]
 [   7  176  382 1519 1343  158  239   21 4937]
 [   0    4    4   16 1741 1307    7   47 8841]
 [   0    5    2    3   65  909    3    1  673]
 [  94  843  368  880  828  324  769   30 4177]
 [   0  120   67  207  184   69   48   99  259]
 [   0    0    0    1    3    0    0    0 2339]]


In [86]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

                 precision    recall  f1-score   support

        Dropcam       0.88      0.96      0.92       819
          IPCam       0.07      0.08      0.08      1118
     NetatmoCam       0.52      0.46      0.49      2878
          Other       0.57      0.17      0.27      8782
SamsungSmartCam       0.40      0.15      0.21     11967
      TPLinkCam       0.31      0.55      0.40      1661
          VConf       0.72      0.09      0.16      8313
         VShare       0.45      0.09      0.16      1053
    WithingsCam       0.10      1.00      0.18      2343

       accuracy                           0.25     38934
      macro avg       0.45      0.39      0.32     38934
   weighted avg       0.49      0.25      0.25     38934



KNN Classifier

In [87]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [88]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test) #avoid data leakage

In [89]:
from math import sqrt
class KNN():
  def __init__(self,k):
    self.k=k
    print(self.k)
  def fit(self,X_train,y_train):
    self.x_train=X_train
    self.y_train=y_train
  def calculate_euclidean(self,sample1,sample2):
    distance=0.0
    for i in range(len(sample1)):
      distance+=(sample1[i]-sample2[i])**2 #Euclidean Distance = sqrt(sum i to N (x1_i – x2_i)^2)
    return sqrt(distance)
  def nearest_neighbors(self,test_sample):
    distances=[]#calculate distances from a test sample to every sample in a training set
    for i in range(len(self.x_train)):
      distances.append((self.y_train[i],self.calculate_euclidean(self.x_train[i],test_sample)))
    distances.sort(key=lambda x:x[1])#sort in ascending order, based on a distance value
    neighbors=[]
    for i in range(self.k): #get first k samples
      neighbors.append(distances[i][0])
    return neighbors
  def predict(self,test_set):
    predictions=[]
    for test_sample in test_set:
      neighbors=self.nearest_neighbors(test_sample)
      labels=[sample for sample in neighbors]
      prediction=max(labels,key=labels.count)
      predictions.append(prediction)
    return predictions

In [90]:
model=KNN(5) #our model
model.fit(X_train,y_train)

5


In [91]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)#The default metric is minkowski, and with p=2 is equivalent to the standard Euclidean metric.
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [92]:
y_pred = classifier.predict(X_test)

In [93]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  773     3     1     2     8     0     9     0     1]
 [    0   933    20    63    16     3    54    21     1]
 [    2    12  2857    32    12     0    27     1     1]
 [    0    31    18  8036    24     5   616    91     3]
 [    3     7    15    19 11881     2    14     6     0]
 [    1     0     2     8     1  1667     1     2     0]
 [   15    37    37   743    18     0  7300    66     6]
 [    1    15     7   274     5     1   151   610     0]
 [    0     0     0     5     2     0     2     1  2333]]


0.9346586531052551

In [95]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

                 precision    recall  f1-score   support

        Dropcam       0.97      0.97      0.97       797
          IPCam       0.90      0.84      0.87      1111
     NetatmoCam       0.97      0.97      0.97      2944
          Other       0.88      0.91      0.89      8824
SamsungSmartCam       0.99      0.99      0.99     11947
      TPLinkCam       0.99      0.99      0.99      1682
          VConf       0.89      0.89      0.89      8222
         VShare       0.76      0.57      0.66      1064
    WithingsCam       0.99      1.00      1.00      2343

       accuracy                           0.93     38934
      macro avg       0.93      0.90      0.91     38934
   weighted avg       0.93      0.93      0.93     38934



LKSVM Classifier

In [ ]:
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Load the dataset
icam = pd.read_csv('C:/Users/Priyanka/Desktop/iCamInspector_GithubRepository/Code/ProcessedNPrunnedAllCombination_ConbinationUNSWOurDataset.csv') #UNSW dataset

# Splitting the data into features and labels
X = icam.iloc[:, :-1]
y = icam.iloc[:, -1]

# Scaling the features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Splitting the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=109)

# Create a svm Classifier
clf = SVC(kernel='linear') 

# Train the model using the training sets
clf.fit(X_train, y_train)

# Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7034447396634503

Random Forest classifier

In [49]:
# split data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.33, random_state = 42)

In [50]:
# check the shape of X_train and X_test
X_train.shape, X_test.shape

((104341, 62), (51393, 62))

In [51]:
#from sklearn.preprocessing import CategoricalEncoder
import category_encoders as ce

# encode categorical variables with ordinal encoding
encoder = ce.OrdinalEncoder(cols=[])
X_train = encoder.fit_transform(X_train)
X_test = encoder.transform(X_test)

In [52]:
# import Random Forest classifier

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# instantiate the classifier 
rfc = RandomForestClassifier(random_state=0)

# fit the model
rfc.fit(X_train, y_train)

# Predict the Test set results
y_pred = rfc.predict(X_test)

# Check accuracy score 
print('Model accuracy score with 10 decision-trees : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with 10 decision-trees : 0.9585


In [53]:
# instantiate the classifier with n_estimators = 100
rfc_100 = RandomForestClassifier(n_estimators=100, random_state=0)

# fit the model to the training set
rfc_100.fit(X_train, y_train)

# Predict on the test set results
y_pred_100 = rfc_100.predict(X_test)

# Check accuracy score 
print('Model accuracy score with 100 decision-trees : {0:0.4f}'. format(accuracy_score(y_test, y_pred_100)))

Model accuracy score with 100 decision-trees : 0.9585


In [54]:
# create the classifier with n_estimators = 100
clf = RandomForestClassifier(n_estimators=100, random_state=0)
# fit the model to the training set
clf.fit(X_train, y_train)

RandomForestClassifier(random_state=0)

In [55]:
# Print the Confusion Matrix and slice it into four pieces
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix\n\n', cm)

Confusion matrix

 [[ 1015     2     0     3     8     0     1     1     0]
 [    0  1319    11    19     9     3    69     7     0]
 [    2     5  3796    16    19     3     3     2     0]
 [    0    16     5 11016     4     1   577    75     0]
 [    9     4    11    11 15673     0    11     1     0]
 [    1     1     0     4     0  2172    11     2     0]
 [    0    17     2   667     0     2 10301    54     0]
 [    0    19     0   291     0     0   150   951     0]
 [    0     0     1     2     0     0     3     0  3015]]


XGBoost Classifier

In [62]:
df = pd.read_csv('D:/Springer_IJIS/ML_code_output/ProcessedNPrunnedAllCombination_ConbinationUNSWOurDataset_XGB.csv')

In [63]:
# Shuffle the dataset
df_shuffled = df.sample(n=len(df))

In [64]:
# Save the shuffled dataset to a new CSV file
df_shuffled.to_csv('C:/Users/Priyanka/Desktop/iCamInspector_GithubRepository/Code/ProcessedNPrunnedAllCombination_ConbinationUNSWOurDataset_Shuffleddataset_XGB.csv', index=False)

In [65]:
df_shuffled = df_shuffled.reset_index(drop=True)

In [66]:
#classification with all the features
masterDS = df_shuffled.values  #masterSelected.values
X = masterDS[:,:-1]
Y = masterDS[:,-1]
print("Xshape: ", X.shape)
print("Yshape: ", Y.shape)

Xshape:  (155734, 62)
Yshape:  (155734,)


In [67]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)
#y_train_xgb = y_train.map({"IPCam": 0, "Other":1, "VConf":2, "VShare": 3})
#X_train, X_test, y_train, y_test = train_test_split(X, Y, Label, test_size=test_size, stratify = labels)

#xgb = XGBClassifier(n_estimators = 400, learning_rate = 0.1, max_depth = 3)
#xgb.fit(X_train.values, y_train)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)
print(y_train.shape)

(116800,)


In [68]:
#import XGBClassifier
from xgboost import XGBClassifier
# declare parameters
params = {
            'objective':'binary:logistic',
            'max_depth': 4,
            #'alpha': 0.1,
            'learning_rate': 1.0,
            'n_estimators':250
         }
                      
# instantiate the classifier 
xgb_clf = XGBClassifier(**params)

# fit the classifier to the training data
xgb_clf.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=1.0, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=250, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [69]:
#alternatively view the parameters of the xgb trained model
print(xgb_clf)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=1.0, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=250, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)


In [70]:
# make predictions on test data
y_pred = xgb_clf.predict(X_test)
print(y_pred.shape)

(38934,)


In [71]:
# check accuracy score
from sklearn.metrics import accuracy_score
print('XGBoost model accuracy score: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

XGBoost model accuracy score: 0.9624


In [72]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred) #our model
print(cm)
accuracy_score(y_test, y_pred)

[[  779     7     1     1     0     0     1     0     2]
 [    8 11855     6     0     0     9     3     0     8]
 [    1     4  2860     0     0    13     1     1     6]
 [    0     1     2  1643     0     2     3     0     4]
 [    0     1     0     0  2391     0     2     0     3]
 [    1    12     5     0     0  1050    19    12    11]
 [    0     2     2     0     1     9  7555    52   459]
 [    0     0     1     0     0     4    96   775   216]
 [    0     6     3     0     0     3   396    63  8563]]


0.9624235886371809