In [1]:
from sklearn import tree
import pandas as pd
import os
import numpy as np
from sklearn import metrics
import matplotlib.pyplot as plt

In [2]:
#load IP camera data
cam_folder = 'D:/IoTCamera_pcapFinal_06062022/CrossValidation_IPCameraOnly/Final csv for df/'
all_files = os.listdir(cam_folder)    
csv_files = list(filter(lambda f: f.endswith('.csv'), all_files))
#for fi in csv_files:
    #print(fi)
print('num csv files = ', len(csv_files)) 

#loading into pandas frame
pd_list = list()
tot_records_count = 0
for fn in csv_files:
    fn_full = cam_folder + fn
    df_cam = pd.read_csv(fn_full, index_col=None, header=0)
    rows = df_cam.shape[0]
    tot_records_count += rows
    print('fn= ', fn, ' rows: ', rows)
    pd_list.append(df_cam)
print('tot records = ', tot_records_count)
#frame_ipcam_Netatmo = pd.concat(pd_list, axis=0, ignore_index=True)
#frame_ipcam_SpyClock = pd.concat(pd_list, axis=0, ignore_index=True)
#frame_ipcam_Canary = pd.concat(pd_list, axis=0, ignore_index=True)
#frame_ipcam_D3D = pd.concat(pd_list, axis=0, ignore_index=True)
frame_ipcam_Ezviz = pd.concat(pd_list, axis=0, ignore_index=True)
#frame_ipcam_SpyBulb = pd.concat(pd_list, axis=0, ignore_index=True)
print('records in final pd frame ipcam: ', frame_ipcam_Ezviz.shape[0])
#print('records in final pd frame ipcam: ', frame_ipcam_SpyBulB.shape[0])

num csv files =  1
fn=  Label4_Ezviz.csv  rows:  3059
tot records =  3059
records in final pd frame ipcam:  3059


In [3]:
#copy the data frames
df_labeled_ipcam_Netatmo = frame_ipcam_Netatmo.copy()
df_labeled_ipcam_SpyClock = frame_ipcam_SpyClock.copy()
df_labeled_ipcam_Canary = frame_ipcam_Canary.copy()
df_labeled_ipcam_D3D = frame_ipcam_D3D.copy()
df_labeled_ipcam_Ezviz = frame_ipcam_Ezviz.copy()
df_labeled_ipcam_SpyBulb = frame_ipcam_SpyBulb.copy()

NameError: name 'frame_ipcam_Netatmo' is not defined

In [77]:
no_label_count = 0
for li in df_labeled_ipcam.Label:
    if li == 'No Label':
        #print(li)
        no_label_count += 1
print('no_label_count = ', no_label_count)

no_label_count =  0


In [78]:
#assign label as 0 to all IP camera traffic, 1 to sharing, and 2 to conf
#df_labeled_ipcam = df_labeled_ipcam.assign(Label=0)
df_labeled_ipcam_Netatmo = df_labeled_ipcam_Netatmo.assign(Label=0)
df_labeled_ipcam_SpyClock = df_labeled_ipcam_SpyClock.assign(Label=1)
df_labeled_ipcam_Canary = df_labeled_ipcam_Canary.assign(Label=2)
df_labeled_ipcam_D3D = df_labeled_ipcam_D3D.assign(Label=3)
df_labeled_ipcam_Ezviz = df_labeled_ipcam_Ezviz.assign(Label=4)
df_labeled_ipcam_SpyBulb = df_labeled_ipcam_SpyBulb.assign(Label=5)

In [79]:
#update labels column
col_names = list(df_labeled_ipcam_Netatmo)
col_names_len = len(col_names)
col_names_onlyX = col_names[7:col_names_len-1] 
print(col_names_onlyX)
print('ft count: ' , len(col_names_onlyX))

['Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg', 'Bwd Pkts/b Avg', 'Bwd Blk

In [80]:
#update labels column
col_names = list(df_labeled_ipcam_SpyClock)
col_names_len = len(col_names)
col_names_onlyX = col_names[7:col_names_len-1] 
print(col_names_onlyX)
print('ft count: ' , len(col_names_onlyX))

['Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg', 'Bwd Pkts/b Avg', 'Bwd Blk

In [81]:
#update labels column
col_names = list(df_labeled_ipcam_Canary)
col_names_len = len(col_names)
col_names_onlyX = col_names[7:col_names_len-1] 
print(col_names_onlyX)
print('ft count: ' , len(col_names_onlyX))

['Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg', 'Bwd Pkts/b Avg', 'Bwd Blk

In [82]:
#update labels column
col_names = list(df_labeled_ipcam_D3D)
col_names_len = len(col_names)
col_names_onlyX = col_names[7:col_names_len-1] 
print(col_names_onlyX)
print('ft count: ' , len(col_names_onlyX))

['Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg', 'Bwd Pkts/b Avg', 'Bwd Blk

In [83]:
#update labels column
col_names = list(df_labeled_ipcam_Ezviz)
col_names_len = len(col_names)
col_names_onlyX = col_names[7:col_names_len-1] 
print(col_names_onlyX)
print('ft count: ' , len(col_names_onlyX))

['Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg', 'Bwd Pkts/b Avg', 'Bwd Blk

In [84]:
#update labels column
col_names = list(df_labeled_ipcam_SpyBulb)
col_names_len = len(col_names)
col_names_onlyX = col_names[7:col_names_len-1] 
print(col_names_onlyX)
print('ft count: ' , len(col_names_onlyX))

['Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg', 'Bwd Pkts/b Avg', 'Bwd Blk

In [85]:
df_cam = pd.concat([df_labeled_ipcam_Netatmo, df_labeled_ipcam_SpyClock, df_labeled_ipcam_Canary, df_labeled_ipcam_D3D, df_labeled_ipcam_Ezviz, df_labeled_ipcam_SpyBulb], axis=0, ignore_index=True)
print('df_labeled_ipcam_Netatmo.shape', df_labeled_ipcam_Netatmo.shape)
print('df_labeled_ipcam_SpyClock.shape', df_labeled_ipcam_SpyClock.shape)
print('df_labeled_ipcam_Canary.shape', df_labeled_ipcam_Canary.shape)
print('df_labeled_ipcam_D3D.shape', df_labeled_ipcam_D3D.shape)
print('df_labeled_ipcam_Ezviz.shape', df_labeled_ipcam_Ezviz.shape)
print('df_labeled_ipcam_SpyBulb.shape', df_labeled_ipcam_SpyBulb.shape)
print('df_cam.shape', df_cam.shape)

df_labeled_ipcam_Netatmo.shape (2519, 84)
df_labeled_ipcam_SpyClock.shape (2275, 84)
df_labeled_ipcam_Canary.shape (1988, 84)
df_labeled_ipcam_D3D.shape (1816, 84)
df_labeled_ipcam_Ezviz.shape (3059, 84)
df_labeled_ipcam_SpyBulb.shape (2499, 84)
df_cam.shape (14156, 84)


In [86]:
#check for columns with NaN
inf_null_col_names = list()
for cni in col_names_onlyX:
    if df_cam[cni].isnull().values.any():
        print(cni,' :  isNull: ', df_cam[cni].isnull().values.any(), ' isNullCount: ',df_cam[cni].isnull().values.sum())
        if cni not in inf_null_col_names:
            inf_null_col_names.append(cni)
    c = np.isinf(df_cam[cni]).values.sum()
    if c > 0:
        print(cni, ' : infCount: ', c)
        if cni not in inf_null_col_names:
            inf_null_col_names.append(cni)
print('num cols with null or inf: ', len(inf_null_col_names))   

num cols with null or inf:  0


In [87]:
#replace NaN with 0 for every column
df_cam.replace([np.inf, -np.inf], np.nan, inplace=True)

#### recheck for inf and nan
for cni in col_names_onlyX:
    if df_cam[cni].isnull().values.any():
        print(cni,' :  isNull: ', df_cam[cni].isnull().values.any(), ' isNullCount: ',df_cam[cni].isnull().values.sum())
        if cni not in inf_null_col_names:
            inf_null_col_names.append(cni)
    c = np.isinf(df_cam[cni]).values.sum()
    if c > 0:
        print(cni, ' : infCount: ', c)
        if cni not in inf_null_col_names:
            inf_null_col_names.append(cni)
print('num cols with null or inf: ', len(inf_null_col_names), ' col names: ', inf_null_col_names) 
print('df_labeled_ipcam_Netatmo.shape', df_labeled_ipcam_Netatmo.shape)

num cols with null or inf:  0  col names:  []
df_labeled_ipcam_Netatmo.shape (2519, 84)


In [89]:
#report pd to a csv file
df_cam.to_csv('D:/IoTCamera_pcapFinal_06062022/CrossValidation_IPCameraOnly/df_with_replaced_inf_nan.csv')
#shuffle the rows in the data frame
shuffled_df_cam = df_cam.sample(frac=1)#frac = 1 ==> consider all the records after shuffling 
print('shuffled_df_cam_conf.shape', shuffled_df_cam.shape)
#print(col_names_onlyX)

shuffled_df_cam_conf.shape (14156, 84)


In [90]:
#extract X vectors and Target Y values
X = shuffled_df_cam.loc[:, col_names_onlyX]
Y = shuffled_df_cam.Label
print(X.shape)

(14156, 76)


In [91]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

In [92]:
#max tree depth = 10
depth = 11 #run the cells of 19, 20, 21 for the other values of depth -- to generate plot
clf = DecisionTreeClassifier(max_depth = depth, random_state = 42)
#scores = cross_val_score(clf, X, Y, cv=10)
#print(scores)

In [93]:
score_list = cross_val_score(clf, X, Y, cv=10)
print('score list: ', score_list)
print('depth = ', depth, ' avg. score = ', np.average(score_list), ' std. score: ', np.std(score_list))

score list:  [0.78672316 0.78954802 0.80155367 0.7980226  0.79378531 0.78954802
 0.8155477  0.79787986 0.80141343 0.81130742]
depth =  11  avg. score =  0.7985329200854445  std. score:  0.00891216467293074


In [94]:
#create train and test set 
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

In [95]:
depth = 11 #take final depth from above analysis
clf = DecisionTreeClassifier(max_depth = depth, random_state = 42)
clf.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=11, random_state=42)

In [96]:
test_pred_decision_tree = clf.predict(X_test)

In [97]:
confusion_matrix = metrics.confusion_matrix(y_test, test_pred_decision_tree)

In [98]:
print(confusion_matrix)

[[664   7   4   1   4 180]
 [  4 559  35   9   2 123]
 [  1 197 382   3   7  77]
 [  2   3  10 457   1  91]
 [  2  17  11   3 910  69]
 [  2  12   9  19   7 788]]


In [99]:
accuracy = metrics.accuracy_score(y_test, test_pred_decision_tree)
precision = metrics.precision_score(y_test, test_pred_decision_tree, average=None)
recall = metrics.recall_score(y_test, test_pred_decision_tree, average =None)
f1 = metrics.f1_score(y_test, test_pred_decision_tree, average=None)

In [100]:
print('accuracy = ', accuracy, ' precision: ', precision, ' recall: ', recall, '  f1: ',f1)

accuracy =  0.8047945205479452  precision:  [0.9837037  0.70314465 0.84700665 0.92886179 0.97744361 0.59337349]  recall:  [0.77209302 0.7636612  0.57271364 0.81028369 0.89920949 0.94145759]   f1:  [0.86514658 0.73215455 0.68336315 0.8655303  0.93669583 0.72794457]


In [125]:
X_train.columns
#X_train.shape

Index(['Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts',
       'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min',
       'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max',
       'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s',
       'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max',
       'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std',
       'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean',
       'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags',
       'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Len',
       'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min',
       'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var',
       'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt',
       'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt',
       'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg',
   

In [102]:
#extract importance
importance = pd.DataFrame({'feature': X_train.columns, 'importance' : np.round(clf.feature_importances_, 10)})
importance.sort_values('importance', ascending=False, inplace = True)

In [103]:
print(importance.shape)
for ri in range(76):
    print(importance.loc[ri,:])

(76, 2)
feature       Flow Duration
importance         0.007002
Name: 0, dtype: object
feature       Tot Fwd Pkts
importance             0.0
Name: 1, dtype: object
feature       Tot Bwd Pkts
importance             0.0
Name: 2, dtype: object
feature       TotLen Fwd Pkts
importance           0.003832
Name: 3, dtype: object
feature       TotLen Bwd Pkts
importance                0.0
Name: 4, dtype: object
feature       Fwd Pkt Len Max
importance                0.0
Name: 5, dtype: object
feature       Fwd Pkt Len Min
importance           0.204549
Name: 6, dtype: object
feature       Fwd Pkt Len Mean
importance             0.00214
Name: 7, dtype: object
feature       Fwd Pkt Len Std
importance                0.0
Name: 8, dtype: object
feature       Bwd Pkt Len Max
importance           0.118188
Name: 9, dtype: object
feature       Bwd Pkt Len Min
importance           0.083907
Name: 10, dtype: object
feature       Bwd Pkt Len Mean
importance            0.001586
Name: 11, dtype: object
featur

In [132]:
#perform experiment to create plot 
impo_count = 0
impo_fts = list()
for i in range(76):
    #enumerate(importance):
    if importance.loc[i,'importance'] > 0.0000001:
        print('i = ', i, ' : ' , col_names_onlyX[i], '  :  ', importance.loc[i,'importance'])
        impo_count += 1
        impo_fts.append(col_names_onlyX[i])
print(' impo count: ', impo_count, '  len(impo_fts): ', len(impo_fts))

i =  0  :  Flow Duration   :   0.0070024461
i =  3  :  TotLen Fwd Pkts   :   0.0038322339
i =  6  :  Fwd Pkt Len Min   :   0.2045489778
i =  7  :  Fwd Pkt Len Mean   :   0.0021397661
i =  9  :  Bwd Pkt Len Max   :   0.1181880629
i =  10  :  Bwd Pkt Len Min   :   0.0839073008
i =  11  :  Bwd Pkt Len Mean   :   0.0015859643
i =  12  :  Bwd Pkt Len Std   :   0.0101841245
i =  13  :  Flow Byts/s   :   0.0043029292
i =  14  :  Flow Pkts/s   :   0.0008965373
i =  15  :  Flow IAT Mean   :   0.0028714374
i =  16  :  Flow IAT Std   :   0.042904188
i =  17  :  Flow IAT Max   :   0.0091159219
i =  18  :  Flow IAT Min   :   0.0023120955
i =  19  :  Fwd IAT Tot   :   0.0007553568
i =  20  :  Fwd IAT Mean   :   0.059908936
i =  21  :  Fwd IAT Std   :   0.0661800648
i =  22  :  Fwd IAT Max   :   0.0017060149
i =  23  :  Fwd IAT Min   :   0.0056126316
i =  24  :  Bwd IAT Tot   :   0.0650737813
i =  25  :  Bwd IAT Mean   :   0.0379557879
i =  26  :  Bwd IAT Std   :   0.0003114734
i =  27  :  Bwd IAT Ma

In [105]:
import seaborn as sns

In [107]:
#with refined features
print(impo_fts)
X = shuffled_df_cam.loc[:, impo_fts]
Y = shuffled_df_cam.Label
print(X.shape)

['Flow Duration', 'TotLen Fwd Pkts', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Subflow Fwd Pkts', 'Subflow Fwd Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts', 'Active Std', 'Active Max', 'Active Min', 'Idle Std', 'Idle Max']
(14156, 45)


In [108]:
#classify with reduced features
depth = 11
clf = DecisionTreeClassifier(max_depth = depth, random_state = 42)
score_list = cross_val_score(clf, X, Y, cv=10)
print('score list: ', score_list)
print('depth = ', depth, ' avg. score = ', np.average(score_list), ' std. score: ', np.std(score_list))

score list:  [0.78742938 0.79519774 0.79943503 0.79872881 0.79378531 0.78319209
 0.79010601 0.77809187 0.8        0.7844523 ]
depth =  11  avg. score =  0.7910418538260366  std. score:  0.007219763843109017


In [109]:
#X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)
depth = 11
clf = DecisionTreeClassifier(max_depth = depth, random_state = 42)
clf = clf.fit(X,Y)
print(clf)

DecisionTreeClassifier(max_depth=11, random_state=42)


In [110]:
import pickle
trained_model_dump_fn = 'iVInspector.pkl'
fhand = open(trained_model_dump_fn,'wb')
pickle.dump(clf,fhand)

In [111]:
fhand_read = open(trained_model_dump_fn,'rb')
loaded_clf = pickle.load(fhand_read)

In [133]:
fn_unknown = 'D:/IoTCamera_pcapFinal_06062022/CrossValidation_IPCameraOnly/df_with_replaced_inf_nan.csv'#name of csv from port mirroring'
df_unknown = pd.read_csv(fn_unknown, index_col=None, header=0)
X_unknown = df_unknown.loc[:, impo_fts]
print(X_unknown)
Y_unknown =df_cam.Label#df_unknown.Label
print(' shape of X unknown: ', X_unknown.shape)

       Flow Duration  TotLen Fwd Pkts  Fwd Pkt Len Min  Fwd Pkt Len Mean  \
0           14737310              0.0                0          0.000000   
1            1640424         109934.0                0       1235.213483   
2            1494713         109934.0                0       1249.250000   
3                368              0.0                0          0.000000   
4            1685337         119946.0                0       1249.437500   
...              ...              ...              ...               ...   
14151            316              0.0                0          0.000000   
14152           2666              0.0                0          0.000000   
14153            311              0.0                0          0.000000   
14154            270              0.0                0          0.000000   
14155            103              0.0                0          0.000000   

       Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  \
0        

In [114]:
predicted_unknown_cases = loaded_clf.predict(X_unknown)
print(predicted_unknown_cases)

[1 0 0 ... 5 5 5]


In [115]:
from collections import Counter
counted_dict = Counter(predicted_unknown_cases)
for key in counted_dict:
    print('key = ', key, ' val = ', counted_dict[key])

key =  1  val =  3521
key =  0  val =  2764
key =  2  val =  1241
key =  4  val =  2949
key =  5  val =  2241
key =  3  val =  1440


In [116]:
from array import *
from collections import Counter
from itertools import chain

In [117]:
pred_prob=clf.predict_proba(X_unknown)#[:,1]
#print(pred_prob)
for ri in range(10):
    print(pred_prob[i])

[1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0.]


In [120]:
pred_prob.shape
max_list = [max(lst) for lst in pred_prob]
count = 0
min_interval = 0.9
max_interval = 1.0
for i in range(14156):
    if max_list[i] <= max_interval and max_list[i] > min_interval:
        print(max_list[i])
        count += 1
#print(count/14156)

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.97

In [121]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier = classifier.fit(X_train,y_train)

In [122]:
print(X_test.shape)
print(y_test.shape)
Counter(y_test)

(4672, 76)
(4672,)


Counter({1: 732, 0: 860, 4: 1012, 2: 667, 5: 837, 3: 564})

In [123]:
y_pred = classifier.predict(X_test)#Accuracy

accuracy = metrics.accuracy_score(y_test, test_pred_decision_tree) 
precision = metrics.precision_score(y_test, test_pred_decision_tree, average=None)
recall = metrics.recall_score(y_test, test_pred_decision_tree, average =None)
f1 = metrics.f1_score(y_test, test_pred_decision_tree, average=None)

print('accuracy = ', accuracy, ' precision: ', precision, ' recall: ', recall, '  f1: ',f1)

confusion_matrix = metrics.confusion_matrix(y_test, test_pred_decision_tree)
print(confusion_matrix)

accuracy =  0.8047945205479452  precision:  [0.9837037  0.70314465 0.84700665 0.92886179 0.97744361 0.59337349]  recall:  [0.77209302 0.7636612  0.57271364 0.81028369 0.89920949 0.94145759]   f1:  [0.86514658 0.73215455 0.68336315 0.8655303  0.93669583 0.72794457]
[[664   7   4   1   4 180]
 [  4 559  35   9   2 123]
 [  1 197 382   3   7  77]
 [  2   3  10 457   1  91]
 [  2  17  11   3 910  69]
 [  2  12   9  19   7 788]]
